; iccavr asm header file for m8HVA - all io memory mapped
; generated by maschag 0.8.7 on 05-21-2009
;-------------------------------------------------------------
;
; Memory info
FLASHEND                =0x1FFF
E2END                   =0x00FF
RAMSTART                =0x0100
RAMEND                  =0x02FF
XRAMEND                 =0 ; Part has no external RAM interface
;
;-------------------------------------------------------------
;
; Port C
PINC                    =0x26
PINC_io                 =0x06  ; for IN/OUT, CBI/SBI, SBIC/SBIS
PORTC                   =0x28
PORTC_io                =0x08  ; for IN/OUT, CBI/SBI, SBIC/SBIS
;
; Port B
PINB                    =0x23
PINB_io                 =0x03  ; for IN/OUT, CBI/SBI, SBIC/SBIS
DDRB                    =0x24
DDRB_io                 =0x04  ; for IN/OUT, CBI/SBI, SBIC/SBIS
PORTB                   =0x25
PORTB_io                =0x05  ; for IN/OUT, CBI/SBI, SBIC/SBIS
;
; Port A
PINA                    =0x20
PINA_io                 =0x00  ; for IN/OUT, CBI/SBI, SBIC/SBIS
DDRA                    =0x21
DDRA_io                 =0x01  ; for IN/OUT, CBI/SBI, SBIC/SBIS
PORTA                   =0x22
PORTA_io                =0x02  ; for IN/OUT, CBI/SBI, SBIC/SBIS
;
; Timer/Counter Interrupts
TIFR0                   =0x35
TIFR0_io                =0x15  ; for IN/OUT, CBI/SBI, SBIC/SBIS
ICF0                    =3
OCF0B                   =2
OCF0A                   =1
TOV0                    =0
TIMSK0                  =0x6E
ICIE1                   =3
OCIE0B                  =2
OCIE0A                  =1
TOIE0                   =0
TIFR1                   =0x36
TIFR1_io                =0x16  ; for IN/OUT, CBI/SBI, SBIC/SBIS
ICF1                    =3
OCF1B                   =2
OCF1A                   =1
TOV1                    =0
TIMSK1                  =0x6F
ICIE1                   =3
OCIE1B                  =2
OCIE1A                  =1
TOIE1                   =0
;
; OSI
OSICSR                  =0x37
OSICSR_io               =0x17  ; for IN/OUT, CBI/SBI, SBIC/SBIS
OSISEL                  =4
OSIST                   =1
OSIEN                   =0
;
; External Interrupts
EIFR                    =0x3C
EIFR_io                 =0x1C  ; for IN/OUT, CBI/SBI, SBIC/SBIS
INTF2                   =2
INTF1                   =1
INTF0                   =0
EIMSK                   =0x3D
EIMSK_io                =0x1D  ; for IN/OUT, CBI/SBI, SBIC/SBIS
INT2                    =2
INT1                    =1
INT0                    =0
EICRA                   =0x69
ISC21                   =5
ISC20                   =4
ISC11                   =3
ISC10                   =2
ISC01                   =1
ISC00                   =0
;
; GPIOR
GPIOR0                  =0x3E
GPIOR0_io               =0x1E  ; for IN/OUT, CBI/SBI, SBIC/SBIS
GPIOR1                  =0x4A
GPIOR1_io               =0x2A  ; for IN/OUT
GPIOR2                  =0x4B
GPIOR2_io               =0x2B  ; for IN/OUT
;
; EEPROM
EECR                    =0x3F
EECR_io                 =0x1F  ; for IN/OUT, CBI/SBI, SBIC/SBIS
EEPM1                   =5
EEPM0                   =4
EERIE                   =3
EEMPE                   =2
EEMWE                   =2
EEPE                    =1
EEWE                    =1
EERE                    =0
EEDR                    =0x40
EEDR_io                 =0x20  ; for IN/OUT
EEAR                    =0x41
EEAR_io                 =0x21  ; for IN/OUT
EEARL                   =0x41
EEARL_io                =0x21  ; for IN/OUT
;
; GTCCR
GTCCR                   =0x43
GTCCR_io                =0x23  ; for IN/OUT
TSM                     =7
PSRSYNC                 =0
PSR10                   =0
;
; Timer/Counter 0
OCR0B                   =0x49
OCR0B_io                =0x29  ; for IN/OUT
OCR0A                   =0x48
OCR0A_io                =0x28  ; for IN/OUT
TCNT0                   =0x46
TCNT0_io                =0x26  ; for IN/OUT
TCNT0L                  =0x46
TCNT0L_io               =0x26  ; for IN/OUT
TCNT0H                  =0x47
TCNT0H_io               =0x27  ; for IN/OUT
TCCR0B                  =0x45
TCCR0B_io               =0x25  ; for IN/OUT
CS02                    =2
CS01                    =1
CS00                    =0
TCCR0A                  =0x44
TCCR0A_io               =0x24  ; for IN/OUT
TCW0                    =7
ICEN0                   =6
ICNC0                   =5
ICES0                   =4
ICS0                    =3
WGM00                   =0
;
; SPI
SPCR                    =0x4C
SPCR_io                 =0x2C  ; for IN/OUT
SPIE                    =7
SPE                     =6
DORD                    =5
MSTR                    =4
CPOL                    =3
CPHA                    =2
SPR1                    =1
SPR0                    =0
SPSR                    =0x4D
SPSR_io                 =0x2D  ; for IN/OUT
SPIF                    =7
WCOL                    =6
SPI2X                   =0
SPDR                    =0x4E
SPDR_io                 =0x2E  ; for IN/OUT
;
; DWDR
DWDR                    =0x51
DWDR_io                 =0x31  ; for IN/OUT
;
; MCU
MCUSR                   =0x54
MCUSR_io                =0x34  ; for IN/OUT
OCDRF                   =4
WDRF                    =3
BODRF                   =2
BORF                    =2
EXTRF                   =1
PORF                    =0
MCUCR                   =0x55
MCUCR_io                =0x35  ; for IN/OUT
CKOE                    =5
PUD                     =4
SMCR                    =0x53
SMCR_io                 =0x33  ; for IN/OUT
SM2                     =3
SM1                     =2
SM0                     =1
SE                      =0
;
; SPM Control and Status Register
SPMCSR                  =0x57
SPMCSR_io               =0x37  ; for IN/OUT
SIGRD                   =5
CTPB                    =4
RFLB                    =3
PGWRT                   =2
PGERS                   =1
SPMEN                   =0
;
; Stack Pointer
SP                      =0x5D
SP_io                   =0x3D  ; for IN/OUT
SPL                     =0x5D
SPL_io                  =0x3D  ; for IN/OUT
SPH                     =0x5E
SPH_io                  =0x3E  ; for IN/OUT
;
; Status REGister
SREG                    =0x5F
SREG_io                 =0x3F  ; for IN/OUT
;
; Watchdog Timer Control Register
WDTCSR                  =0x60
WDTCR                   =0x60
WDIF                    =7
WDIE                    =6
WDP3                    =5
WDCE                    =4
WDE                     =3
WDP2                    =2
WDP1                    =1
WDP0                    =0
;
; clock prescaler control register
CLKPR                   =0x61
CLKPCE                  =7
; #define  CLKPS3   3
; #define  CLKPS2   2
CLKPS1                  =1
CLKPS0                  =0
;
; PRR
PRR0                    =0x64
PRVRM                   =6
PRSPI                   =3
PRTIM1                  =2
PRTIM0                  =1
PRVADC                  =0
;
; Oscillator Calibration Register
FOSCCAL                 =0x66
;
; VADC
VADC                    =0x78
VADCL                   =0x78
VADCH                   =0x79
VADCSR                  =0x7A
VADEN                   =3
VADSC                   =2
VADCCIF                 =1
VADCCIE                 =0
VADMUX                  =0x7C
VADMUX3                 =3
VADMUX2                 =2
VADMUX1                 =1
VADMUX0                 =0
;
; DIDR
DIDR0                   =0x7E
PA1DID                  =1
PA0DID                  =1
;
; Timer/Counter1
OCR1B                   =0x89
OCR1A                   =0x88
TCNT1                   =0x84
TCNT1L                  =0x84
TCNT1H                  =0x85
TCCR1B                  =0x81
CS12                    =2
CS11                    =1
CS10                    =0
TCCR1A                  =0x80
TCW1                    =7
ICEN1                   =6
ICNC1                   =5
ICES1                   =4
ICS1                    =3
WGM10                   =0
;
; RO
ROCR                    =0xC8
ROCS                    =7
ROCWIF                  =1
ROCWIE                  =0
;
; BGC
BGCCR                   =0xD0
BGD                     =7
BGCRR                   =0xD1
;
; CAD
CADAC                   =0xE0
CADAC0                  =0xE0
CADAC1                  =0xE1
CADAC2                  =0xE2
CADAC3                  =0xE3
CADCSRA                 =0xE4
CADEN                   =7
CADPOL                  =6
CADUB                   =5
CADAS1                  =4
CADAS0                  =3
CADSI1                  =2
CADSI0                  =1
CADSE                   =0
CADCSRB                 =0xE5
CADACIE                 =6
CADICIE                 =4
CADACIF                 =2
CADRCIF                 =1
CADICIF                 =0
CADRC                   =0xE6
CADIC                   =0xE8
CADICL                  =0xE8
CADICH                  =0xE9
;
; FCSR
FCSR                    =0xF0
DUVRD                   =3
CPS                     =2
DFE                     =1
CFE                     =0
;
; BP
BPIMSK                  =0xF2
SCIE                    =4
DOCIE                   =3
COCIE                   =2
DHCIE                   =1
CHCIE                   =0
BPIFR                   =0xF3
SCIF                    =4
DOCIF                   =3
COCIF                   =2
DHCIF                   =1
CHCIF                   =0
BPSCD                   =0xF5
BPDOCD                  =0xF6
BPCOCD                  =0xF7
BPDHCD                  =0xF8
BPCHCD                  =0xF9
BPSCTR                  =0xFA
BPOCTR                  =0xFB
BPHCTR                  =0xFC
BPCR                    =0xFD
SCD                     =4
DOCD                    =3
COCD                    =2
DHCD                    =1
CHCD                    =0
BPPLR                   =0xFE
BPPLE                   =1
BPPL                    =0
;
; bits
;
; Port A
PORTA1                  =1
PORTA0                  =0
PA1                     =1
PA0                     =0
DDA1                    =1
DDA0                    =0
PINA1                   =1
PINA0                   =0
;
; Port B
PORTB3                  =3
PORTB2                  =2
PORTB1                  =1
PORTB0                  =0
PB3                     =3
PB2                     =2
PB1                     =1
PB0                     =0
DDB3                    =3
DDB2                    =2
DDB1                    =1
DDB0                    =0
PINB3                   =3
PINB2                   =2
PINB1                   =1
PINB0                   =0
;
; Port C
PORTC0                  =0
PC0                     =0
PINC0                   =0
;
; Lock and Fuse Bits with LPM/SPM instructions
;
; lock bits
LB2                     =1
LB1                     =0
;
; fuses low bits
WDTON                   =7
EESAVE                  =6
SPIEN                   =5
DWEN                    =4
SELFPRGEN               =3
SUT2                    =2
SUT1                    =1
SUT0                    =0
;
; fuses high bits
OSCSEL1                 =1
OSCSEL0                 =0
;
; ------------------------------------------------------------
;
; Interrupt Vector Macros
;
.macro set_vector_BPINT
 .area vector (abs)
 .org  0x02
  rjmp @0
 .area text
.endmacro
.macro set_vector_PCINT1
 .area vector (abs)
 .org  0x0A
  rjmp @0
 .area text
.endmacro
.macro set_vector_INT0
 .area vector (abs)
 .org  0x06
  rjmp @0
 .area text
.endmacro
.macro set_vector_EXT_INT0
 .area vector (abs)
 .org  0x06
  rjmp @0
 .area text
.endmacro
.macro set_vector_INT1
 .area vector (abs)
 .org  0x08
  rjmp @0
 .area text
.endmacro
.macro set_vector_EXT_INT1
 .area vector (abs)
 .org  0x08
  rjmp @0
 .area text
.endmacro
.macro set_vector_INT2
 .area vector (abs)
 .org  0x0A
  rjmp @0
 .area text
.endmacro
.macro set_vector_EXT_INT2
 .area vector (abs)
 .org  0x0A
  rjmp @0
 .area text
.endmacro
.macro set_vector_WDT
 .area vector (abs)
 .org  0x0C
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER1_CAPT
 .area vector (abs)
 .org  0x0E
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER1_COMPA
 .area vector (abs)
 .org  0x10
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER1_COMPB
 .area vector (abs)
 .org  0x12
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER1_OVF
 .area vector (abs)
 .org  0x14
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM1_CAPT
 .area vector (abs)
 .org  0x0E
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM1_COMPA
 .area vector (abs)
 .org  0x10
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM1_COMPB
 .area vector (abs)
 .org  0x12
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM1_OVF
 .area vector (abs)
 .org  0x14
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER0_CAPT
 .area vector (abs)
 .org  0x16
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER0_COMPA
 .area vector (abs)
 .org  0x18
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER0_COMPB
 .area vector (abs)
 .org  0x1A
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER0_OVF
 .area vector (abs)
 .org  0x1C
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM0_CAPT
 .area vector (abs)
 .org  0x16
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM0_COMPA
 .area vector (abs)
 .org  0x18
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM0_COMPB
 .area vector (abs)
 .org  0x1A
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM0_OVF
 .area vector (abs)
 .org  0x1C
  rjmp @0
 .area text
.endmacro
.macro set_vector_SPI_STC
 .area vector (abs)
 .org  0x1E
  rjmp @0
 .area text
.endmacro
.macro set_vector_VADC
 .area vector (abs)
 .org  0x20
  rjmp @0
 .area text
.endmacro
.macro set_vector_CCADC_CONV
 .area vector (abs)
 .org  0x22
  rjmp @0
 .area text
.endmacro
.macro set_vector_CCADC_REG_CUR
 .area vector (abs)
 .org  0x24
  rjmp @0
 .area text
.endmacro
.macro set_vector_CCADC_ACC
 .area vector (abs)
 .org  0x26
  rjmp @0
 .area text
.endmacro
.macro set_vector_EE_RDY
 .area vector (abs)
 .org  0x28
  rjmp @0
 .area text
.endmacro
.macro set_vector_EE_READY
 .area vector (abs)
 .org  0x28
  rjmp @0
 .area text
.endmacro
;------
;<eof>
