; iccavr asm header file for m32
; generated by maschag 0.8.7 on 04-15-2009
;-------------------------------------------------------------
;
; Memory info
FLASHEND                =0x7FFF
E2END                   =0x03FF
RAMSTART                =0x0060
RAMEND                  =0x085F
XRAMEND                 =0 ; Part has no external RAM interface
;
;-------------------------------------------------------------
;
; 2 wire serial interface
TWBR                    =0x00
TWSR                    =0x01
TWPS1                   =1
TWPS0                   =0
TWCR                    =0x36
TWINT                   =7
TWEA                    =6
TWSTA                   =5
TWSTO                   =4
TWWC                    =3
TWEN                    =2
TWIE                    =0
TWAR                    =0x02
TWGCE                   =0
TWDR                    =0x03
;
; ADC
ADC                     =0x04
ADCL                    =0x04
ADCH                    =0x05
ADCSR                   =0x06
ADCSRA                  =0x06
ADEN                    =7
ADSC                    =6
ADATE                   =5
ADIF                    =4
ADIE                    =3
ADPS2                   =2
ADPS1                   =1
ADPS0                   =0
ADMUX                   =0x07
REFS1                   =7
REFS0                   =6
ADLAR                   =5
MUX4                    =4
MUX3                    =3
MUX2                    =2
MUX1                    =1
MUX0                    =0
;
; Analog Comparator
ACSR                    =0x08
ACD                     =7
ACBG                    =6
ACO                     =5
ACI                     =4
ACIE                    =3
ACIC                    =2
ACIS1                   =1
ACIS0                   =0
;
; USART
UBRRHI                  =0x20
UBRRH                   =0x20
URSEL                   =7
UBRR                    =0x09
UBRRL                   =0x09
UCSRC                   =0x20
URSEL                   =7
UMSEL                   =6
UPM1                    =5
UPM0                    =4
USBS                    =3
UCSZ1                   =2
UCSZ0                   =1
UCPOL                   =0
UCSRB                   =0x0A
RXCIE                   =7
TXCIE                   =6
UDRIE                   =5
RXEN                    =4
TXEN                    =3
UCSZ2                   =2
RXB8                    =1
TXB8                    =0
UCSRA                   =0x0B
RXC                     =7
TXC                     =6
UDRE                    =5
FE                      =4
DOR                     =3
OVR                     =3
PE                      =2
U2X                     =1
MPCM                    =0
UDR                     =0x0C
;
; SPI
SPCR                    =0x0D
SPIE                    =7
SPE                     =6
DORD                    =5
MSTR                    =4
CPOL                    =3
CPHA                    =2
SPR1                    =1
SPR0                    =0
SPSR                    =0x0E
SPIF                    =7
WCOL                    =6
SPI2X                   =0
SPDR                    =0x0F
;
; Port D
PIND                    =0x10
DDRD                    =0x11
PORTD                   =0x12
;
; Port C
PINC                    =0x13
DDRC                    =0x14
PORTC                   =0x15
;
; Port B
PINB                    =0x16
DDRB                    =0x17
PORTB                   =0x18
;
; Port A
PINA                    =0x19
DDRA                    =0x1A
PORTA                   =0x1B
;
; EEPROM
EECR                    =0x1C
EERIE                   =3
EEMWE                   =2
EEWE                    =1
EERE                    =0
EEDR                    =0x1D
EEAR                    =0x1E
EEARL                   =0x1E
EEARH                   =0x1F
;
; Watchdog Timer Control Register
WDTCR                   =0x21
WDTOE                   =4
WDE                     =3
WDP2                    =2
WDP1                    =1
WDP0                    =0
;
; Timer/Counter 2
ASSR                    =0x22
AS2                     =3
TCN2UB                  =2
OCR2UB                  =1
TCR2UB                  =0
OCR2                    =0x23
TCNT2                   =0x24
TCCR2                   =0x25
FOC2                    =7
WGM20                   =6
COM21                   =5
COM20                   =4
WGM21                   =3
CS22                    =2
CS21                    =1
CS20                    =0
;
; Timer/Counter 1
ICR1                    =0x26
ICR1L                   =0x26
ICR1H                   =0x27
OCR1B                   =0x28
OCR1BL                  =0x28
OCR1BH                  =0x29
OCR1A                   =0x2A
OCR1AL                  =0x2A
OCR1AH                  =0x2B
TCNT1                   =0x2C
TCNT1L                  =0x2C
TCNT1H                  =0x2D
TCCR1B                  =0x2E
ICNC1                   =7
ICES1                   =6
WGM13                   =4
WGM12                   =3
CS12                    =2
CS11                    =1
CS10                    =0
TCCR1A                  =0x2F
COM1A1                  =7
COM1A0                  =6
COM1B1                  =5
COM1B0                  =4
FOC1A                   =3
FOC1B                   =2
WGM11                   =1
WGM10                   =0
;
; Special Function I/O register
SFIOR                   =0x30
ADTS2                   =7
ADTS1                   =6
ADTS0                   =5
ADHSM                   =4
ACME                    =3
PUD                     =2
PSR2                    =1
PSR10                   =0
;
; Oscillator Calibration
OSCCAL                  =0x31
;
; On-Chip Debug register
OCDR                    =0x31
;
; Timer/Counter 0
OCR0                    =0x3C
TCNT0                   =0x32
TCCR0                   =0x33
FOC0                    =7
WGM00                   =6
COM01                   =5
COM00                   =4
WGM01                   =3
CS02                    =2
CS01                    =1
CS00                    =0
;
; MCU general
MCUCSR                  =0x34
MCUSR                   =0x34
JTD                     =7
ISC2                    =6
JTRF                    =4
WDRF                    =3
BORF                    =2
EXTRF                   =1
PORF                    =0
MCUCR                   =0x35
SE                      =7
SM2                     =6
SM1                     =5
SM0                     =4
ISC11                   =3
ISC10                   =2
ISC01                   =1
ISC00                   =0
;
; SPM Conrol Register
SPMCR                   =0x37
SPMIE                   =7
RWWSB                   =6
RWWSRE                  =4
BLBSET                  =3
PGWRT                   =2
PGERS                   =1
SPMEN                   =0
;
; Timer/Counter Interrupts
TIFR                    =0x38
OCF2                    =7
TOV2                    =6
ICF1                    =5
OCF1A                   =4
OCF1B                   =3
TOV1                    =2
OCF0                    =1
TOV0                    =0
TIMSK                   =0x39
OCIE2                   =7
TOIE2                   =6
TICIE1                  =5
OCIE1A                  =4
OCIE1B                  =3
TOIE1                   =2
OCIE0                   =1
TOIE0                   =0
;
; General Interrupts
GIFR                    =0x3A
INTF1                   =7
INTF0                   =6
INTF2                   =5
GICR                    =0x3B
INT1                    =7
INT0                    =6
INT2                    =5
IVSEL                   =1
IVCE                    =0
;
; Stack Pointer
SP                      =0x3D
SPL                     =0x3D
SPH                     =0x3E
;
; Status REGister
SREG                    =0x3F
;
; Port A bits
PORTA7                  =7
PORTA6                  =6
PORTA5                  =5
PORTA4                  =4
PORTA3                  =3
PORTA2                  =2
PORTA1                  =1
PORTA0                  =0
PA7                     =7
PA6                     =6
PA5                     =5
PA4                     =4
PA3                     =3
PA2                     =2
PA1                     =1
PA0                     =0
DDA7                    =7
DDA6                    =6
DDA5                    =5
DDA4                    =4
DDA3                    =3
DDA2                    =2
DDA1                    =1
DDA0                    =0
PINA7                   =7
PINA6                   =6
PINA5                   =5
PINA4                   =4
PINA3                   =3
PINA2                   =2
PINA1                   =1
PINA0                   =0
;
; Port B bits
PORTB7                  =7
PORTB6                  =6
PORTB5                  =5
PORTB4                  =4
PORTB3                  =3
PORTB2                  =2
PORTB1                  =1
PORTB0                  =0
PB7                     =7
PB6                     =6
PB5                     =5
PB4                     =4
PB3                     =3
PB2                     =2
PB1                     =1
PB0                     =0
DDB7                    =7
DDB6                    =6
DDB5                    =5
DDB4                    =4
DDB3                    =3
DDB2                    =2
DDB1                    =1
DDB0                    =0
PINB7                   =7
PINB6                   =6
PINB5                   =5
PINB4                   =4
PINB3                   =3
PINB2                   =2
PINB1                   =1
PINB0                   =0
;
; Port C bits
PORTC7                  =7
PORTC6                  =6
PORTC5                  =5
PORTC4                  =4
PORTC3                  =3
PORTC2                  =2
PORTC1                  =1
PORTC0                  =0
PC7                     =7
PC6                     =6
PC5                     =5
PC4                     =4
PC3                     =3
PC2                     =2
PC1                     =1
PC0                     =0
DDC7                    =7
DDC6                    =6
DDC5                    =5
DDC4                    =4
DDC3                    =3
DDC2                    =2
DDC1                    =1
DDC0                    =0
PINC7                   =7
PINC6                   =6
PINC5                   =5
PINC4                   =4
PINC3                   =3
PINC2                   =2
PINC1                   =1
PINC0                   =0
;
; Port D bits
PORTD7                  =7
PORTD6                  =6
PORTD5                  =5
PORTD4                  =4
PORTD3                  =3
PORTD2                  =2
PORTD1                  =1
PORTD0                  =0
PD7                     =7
PD6                     =6
PD5                     =5
PD4                     =4
PD3                     =3
PD2                     =2
PD1                     =1
PD0                     =0
DDD7                    =7
DDD6                    =6
DDD5                    =5
DDD4                    =4
DDD3                    =3
DDD2                    =2
DDD1                    =1
DDD0                    =0
PIND7                   =7
PIND6                   =6
PIND5                   =5
PIND4                   =4
PIND3                   =3
PIND2                   =2
PIND1                   =1
PIND0                   =0
;
; Lock and Fuse Bits with LPM/SPM instructions
;
; lock bits
BLB12                   =5
BLB11                   =4
BLB02                   =3
BLB01                   =2
LB2                     =1
LB1                     =0
;
; fuses low bits
BODLEVEL                =7
BODEN                   =6
SUT1                    =5
SUT0                    =4
CKSEL3                  =3
CKSEL2                  =2
CKSEL1                  =1
CKSEL0                  =0
;
; fuses high bits
OCDEN                   =7
JTAGEN                  =6
SPIEN                   =5
CKOPT                   =4
EESAVE                  =3
BOOTSZ1                 =2
BOOTSZ0                 =1
BOOTRST                 =0
;
; ------------------------------------------------------------
;
; Interrupt Vector Macros
;
.macro set_vector_INT0
 .area vector (abs)
 .org  0x04
  jmp  @0
 .area text
.endmacro
.macro set_vector_EXT_INT0
 .area vector (abs)
 .org  0x04
  jmp  @0
 .area text
.endmacro
.macro set_vector_INT1
 .area vector (abs)
 .org  0x08
  jmp  @0
 .area text
.endmacro
.macro set_vector_EXT_INT1
 .area vector (abs)
 .org  0x08
  jmp  @0
 .area text
.endmacro
.macro set_vector_INT2
 .area vector (abs)
 .org  0x0C
  jmp  @0
 .area text
.endmacro
.macro set_vector_EXT_INT2
 .area vector (abs)
 .org  0x0C
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIMER2_COMPA
 .area vector (abs)
 .org  0x10
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIMER2_COMP
 .area vector (abs)
 .org  0x10
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIM2_COMP
 .area vector (abs)
 .org  0x10
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIMER2_OVF
 .area vector (abs)
 .org  0x14
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIM2_OVF
 .area vector (abs)
 .org  0x14
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIMER1_CAPT
 .area vector (abs)
 .org  0x18
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIM1_CAPT
 .area vector (abs)
 .org  0x18
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIMER1_COMPA
 .area vector (abs)
 .org  0x1C
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIM1_COMPA
 .area vector (abs)
 .org  0x1C
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIMER1_COMPB
 .area vector (abs)
 .org  0x20
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIM1_COMPB
 .area vector (abs)
 .org  0x20
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIMER1_OVF
 .area vector (abs)
 .org  0x24
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIM1_OVF
 .area vector (abs)
 .org  0x24
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIMER0_COMPA
 .area vector (abs)
 .org  0x28
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIMER0_COMP
 .area vector (abs)
 .org  0x28
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIM0_COMP
 .area vector (abs)
 .org  0x28
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIMER0_OVF
 .area vector (abs)
 .org  0x2C
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIM0_OVF
 .area vector (abs)
 .org  0x2C
  jmp  @0
 .area text
.endmacro
.macro set_vector_SPI_STC
 .area vector (abs)
 .org  0x30
  jmp  @0
 .area text
.endmacro
.macro set_vector_USART_RX
 .area vector (abs)
 .org  0x34
  jmp  @0
 .area text
.endmacro
.macro set_vector_USART_RXC
 .area vector (abs)
 .org  0x34
  jmp  @0
 .area text
.endmacro
.macro set_vector_USART0_RX
 .area vector (abs)
 .org  0x34
  jmp  @0
 .area text
.endmacro
.macro set_vector_USART0_RXC
 .area vector (abs)
 .org  0x34
  jmp  @0
 .area text
.endmacro
.macro set_vector_USART_DRE
 .area vector (abs)
 .org  0x38
  jmp  @0
 .area text
.endmacro
.macro set_vector_USART_UDRE
 .area vector (abs)
 .org  0x38
  jmp  @0
 .area text
.endmacro
.macro set_vector_USART0_DRE
 .area vector (abs)
 .org  0x38
  jmp  @0
 .area text
.endmacro
.macro set_vector_USART0_UDRE
 .area vector (abs)
 .org  0x38
  jmp  @0
 .area text
.endmacro
.macro set_vector_USART_TX
 .area vector (abs)
 .org  0x3C
  jmp  @0
 .area text
.endmacro
.macro set_vector_USART_TXC
 .area vector (abs)
 .org  0x3C
  jmp  @0
 .area text
.endmacro
.macro set_vector_USART0_TX
 .area vector (abs)
 .org  0x3C
  jmp  @0
 .area text
.endmacro
.macro set_vector_USART0_TXC
 .area vector (abs)
 .org  0x3C
  jmp  @0
 .area text
.endmacro
.macro set_vector_ADC
 .area vector (abs)
 .org  0x40
  jmp  @0
 .area text
.endmacro
.macro set_vector_EE_RDY
 .area vector (abs)
 .org  0x44
  jmp  @0
 .area text
.endmacro
.macro set_vector_EE_READY
 .area vector (abs)
 .org  0x44
  jmp  @0
 .area text
.endmacro
.macro set_vector_ANA_COMP
 .area vector (abs)
 .org  0x48
  jmp  @0
 .area text
.endmacro
.macro set_vector_ANALOG_COMP
 .area vector (abs)
 .org  0x48
  jmp  @0
 .area text
.endmacro
.macro set_vector_TWI
 .area vector (abs)
 .org  0x4C
  jmp  @0
 .area text
.endmacro
.macro set_vector_TWSI
 .area vector (abs)
 .org  0x4C
  jmp  @0
 .area text
.endmacro
.macro set_vector_SPM_RDY
 .area vector (abs)
 .org  0x50
  jmp  @0
 .area text
.endmacro
.macro set_vector_SPM_READY
 .area vector (abs)
 .org  0x50
  jmp  @0
 .area text
.endmacro
;------
;<eof>
