; iccavr asm header file for m64 - all io memory mapped
; generated by maschag 0.8.7 on 04-15-2009
;-------------------------------------------------------------
;
; Memory info
FLASHEND                =0xFFFF
E2END                   =0x07FF
RAMSTART                =0x0100
RAMEND                  =0x10FF
XRAMEND                 =0xFFFF
;
;-------------------------------------------------------------
;
; Port G
PING                    =0x63
DDRG                    =0x64
PORTG                   =0x65
;
; Port F
PINF                    =0x20
PINF_io                 =0x00  ; for IN/OUT, CBI/SBI, SBIC/SBIS
DDRF                    =0x61
PORTF                   =0x62
;
; Port E
PINE                    =0x21
PINE_io                 =0x01  ; for IN/OUT, CBI/SBI, SBIC/SBIS
DDRE                    =0x22
DDRE_io                 =0x02  ; for IN/OUT, CBI/SBI, SBIC/SBIS
PORTE                   =0x23
PORTE_io                =0x03  ; for IN/OUT, CBI/SBI, SBIC/SBIS
;
; Port D
PIND                    =0x30
PIND_io                 =0x10  ; for IN/OUT, CBI/SBI, SBIC/SBIS
DDRD                    =0x31
DDRD_io                 =0x11  ; for IN/OUT, CBI/SBI, SBIC/SBIS
PORTD                   =0x32
PORTD_io                =0x12  ; for IN/OUT, CBI/SBI, SBIC/SBIS
;
; Port C
PINC                    =0x33
PINC_io                 =0x13  ; for IN/OUT, CBI/SBI, SBIC/SBIS
DDRC                    =0x34
DDRC_io                 =0x14  ; for IN/OUT, CBI/SBI, SBIC/SBIS
PORTC                   =0x35
PORTC_io                =0x15  ; for IN/OUT, CBI/SBI, SBIC/SBIS
;
; Port B
PINB                    =0x36
PINB_io                 =0x16  ; for IN/OUT, CBI/SBI, SBIC/SBIS
DDRB                    =0x37
DDRB_io                 =0x17  ; for IN/OUT, CBI/SBI, SBIC/SBIS
PORTB                   =0x38
PORTB_io                =0x18  ; for IN/OUT, CBI/SBI, SBIC/SBIS
;
; Port A
PINA                    =0x39
PINA_io                 =0x19  ; for IN/OUT, CBI/SBI, SBIC/SBIS
DDRA                    =0x3A
DDRA_io                 =0x1A  ; for IN/OUT, CBI/SBI, SBIC/SBIS
PORTA                   =0x3B
PORTA_io                =0x1B  ; for IN/OUT, CBI/SBI, SBIC/SBIS
;
; ADC
ADC                     =0x24
ADC_io                  =0x04  ; for IN/OUT, CBI/SBI, SBIC/SBIS
ADCL                    =0x24
ADCL_io                 =0x04  ; for IN/OUT, CBI/SBI, SBIC/SBIS
ADCH                    =0x25
ADCH_io                 =0x05  ; for IN/OUT, CBI/SBI, SBIC/SBIS
ADCSRB                  =0x8E
ADTS2                   =2
ADTS1                   =1
ADTS0                   =0
ADCSRA                  =0x26
ADCSRA_io               =0x06  ; for IN/OUT, CBI/SBI, SBIC/SBIS
ADEN                    =7
ADSC                    =6
ADFR                    =5
ADATE                   =5
ADIF                    =4
ADIE                    =3
ADPS2                   =2
ADPS1                   =1
ADPS0                   =0
ADMUX                   =0x27
ADMUX_io                =0x07  ; for IN/OUT, CBI/SBI, SBIC/SBIS
REFS1                   =7
REFS0                   =6
ADLAR                   =5
MUX4                    =4
MUX3                    =3
MUX2                    =2
MUX1                    =1
MUX0                    =0
;
; Analog Comparator Control and Status Register
ACSR                    =0x28
ACSR_io                 =0x08  ; for IN/OUT, CBI/SBI, SBIC/SBIS
ACD                     =7
ACBG                    =6
ACO                     =5
ACI                     =4
ACIE                    =3
ACIC                    =2
ACIS1                   =1
ACIS0                   =0
;
; USART0
UBRR0H                  =0x90
UBRR0L                  =0x29
UBRR0L_io               =0x09  ; for IN/OUT, CBI/SBI, SBIC/SBIS
UCSR0C                  =0x95
UMSEL0                  =6
UPM01                   =5
UPM00                   =4
USBS0                   =3
UCSZ01                  =2
UCSZ00                  =1
UCPOL0                  =0
UCSR0B                  =0x2A
UCSR0B_io               =0x0A  ; for IN/OUT, CBI/SBI, SBIC/SBIS
RXCIE0                  =7
TXCIE0                  =6
UDRIE0                  =5
RXEN0                   =4
TXEN0                   =3
UCSZ02                  =2
RXB80                   =1
TXB80                   =0
UCSR0A                  =0x2B
UCSR0A_io               =0x0B  ; for IN/OUT, CBI/SBI, SBIC/SBIS
RXC0                    =7
TXC0                    =6
UDRE0                   =5
FE0                     =4
DOR0                    =3
UPE0                    =2
U2X0                    =1
MPCM0                   =0
UDR0                    =0x2C
UDR0_io                 =0x0C  ; for IN/OUT, CBI/SBI, SBIC/SBIS
;
; USART1
UBRR1H                  =0x98
UBRR1L                  =0x99
UCSR1C                  =0x9D
UMSEL1                  =6
UPM11                   =5
UPM10                   =4
USBS1                   =3
UCSZ11                  =2
UCSZ10                  =1
UCPOL1                  =0
UCSR1B                  =0x9A
RXCIE1                  =7
TXCIE1                  =6
UDRIE1                  =5
RXEN1                   =4
TXEN1                   =3
UCSZ12                  =2
RXB81                   =1
TXB81                   =0
UCSR1A                  =0x9B
RXC1                    =7
TXC1                    =6
UDRE1                   =5
FE1                     =4
DOR1                    =3
UPE1                    =2
U2X1                    =1
MPCM1                   =0
UDR1                    =0x9C
;
; 2-wire SI
TWBR                    =0x70
TWSR                    =0x71
TWPS1                   =1
TWPS0                   =0
TWAR                    =0x72
TWGCE                   =0
TWDR                    =0x73
TWCR                    =0x74
TWINT                   =7
TWEA                    =6
TWSTA                   =5
TWSTO                   =4
TWWC                    =3
TWEN                    =2
TWIE                    =0
;
; SPI
SPCR                    =0x2D
SPCR_io                 =0x0D  ; for IN/OUT, CBI/SBI, SBIC/SBIS
SPIE                    =7
SPE                     =6
DORD                    =5
MSTR                    =4
CPOL                    =3
CPHA                    =2
SPR1                    =1
SPR0                    =0
SPSR                    =0x2E
SPSR_io                 =0x0E  ; for IN/OUT, CBI/SBI, SBIC/SBIS
SPIF                    =7
WCOL                    =6
SPI2X                   =0
SPDR                    =0x2F
SPDR_io                 =0x0F  ; for IN/OUT, CBI/SBI, SBIC/SBIS
;
; EEPROM
EECR                    =0x3C
EECR_io                 =0x1C  ; for IN/OUT, CBI/SBI, SBIC/SBIS
EERIE                   =3
EEMWE                   =2
EEWE                    =1
EERE                    =0
EEDR                    =0x3D
EEDR_io                 =0x1D  ; for IN/OUT, CBI/SBI, SBIC/SBIS
EEAR                    =0x3E
EEAR_io                 =0x1E  ; for IN/OUT, CBI/SBI, SBIC/SBIS
EEARL                   =0x3E
EEARL_io                =0x1E  ; for IN/OUT, CBI/SBI, SBIC/SBIS
EEARH                   =0x3F
EEARH_io                =0x1F  ; for IN/OUT, CBI/SBI, SBIC/SBIS
;
; Special Function IO Register
SFIOR                   =0x40
SFIOR_io                =0x20  ; for IN/OUT
TSM                     =7
ADHSM                   =4
ACME                    =3
PUD                     =2
PSR0                    =1
PSR321                  =0
;
; Watchdog Timer Control Register
WDTCR                   =0x41
WDTCR_io                =0x21  ; for IN/OUT
WDCE                    =4
WDE                     =3
WDP2                    =2
WDP1                    =1
WDP0                    =0
;
; OCDR
OCDR                    =0x42
OCDR_io                 =0x22  ; for IN/OUT
IDRD                    =7
;
; Timer/Counter3
ICR3                    =0x80
ICR3L                   =0x80
ICR3H                   =0x81
OCR3C                   =0x82
OCR3CL                  =0x82
OCR3CH                  =0x83
OCR3B                   =0x84
OCR3BL                  =0x84
OCR3BH                  =0x85
OCR3A                   =0x86
OCR3AL                  =0x86
OCR3AH                  =0x87
TCNT3                   =0x88
TCNT3L                  =0x88
TCNT3H                  =0x89
TCCR3C                  =0x8C
FOC3A                   =7
FOC3B                   =6
FOC3C                   =5
TCCR3B                  =0x8A
ICNC3                   =7
ICES3                   =6
WGM33                   =4
WGM32                   =3
CS32                    =2
CS31                    =1
CS30                    =0
TCCR3A                  =0x8B
COM3A1                  =7
COM3A0                  =6
COM3B1                  =5
COM3B0                  =4
COM3C1                  =3
COM3C0                  =2
WGM31                   =1
WGM30                   =0
;
; Timer/Counter2
OCR2                    =0x43
OCR2_io                 =0x23  ; for IN/OUT
TCNT2                   =0x44
TCNT2_io                =0x24  ; for IN/OUT
TCCR2                   =0x45
TCCR2_io                =0x25  ; for IN/OUT
FOC2                    =7
WGM20                   =6
COM21                   =5
COM20                   =4
WGM21                   =3
CS22                    =2
CS21                    =1
CS20                    =0
;
; Timer/Counter1
ICR1                    =0x46
ICR1_io                 =0x26  ; for IN/OUT
ICR1L                   =0x46
ICR1L_io                =0x26  ; for IN/OUT
ICR1H                   =0x47
ICR1H_io                =0x27  ; for IN/OUT
OCR1C                   =0x78
OCR1CL                  =0x78
OCR1CH                  =0x79
OCR1B                   =0x48
OCR1B_io                =0x28  ; for IN/OUT
OCR1BL                  =0x48
OCR1BL_io               =0x28  ; for IN/OUT
OCR1BH                  =0x49
OCR1BH_io               =0x29  ; for IN/OUT
OCR1A                   =0x4A
OCR1A_io                =0x2A  ; for IN/OUT
OCR1AL                  =0x4A
OCR1AL_io               =0x2A  ; for IN/OUT
OCR1AH                  =0x4B
OCR1AH_io               =0x2B  ; for IN/OUT
TCNT1                   =0x4C
TCNT1_io                =0x2C  ; for IN/OUT
TCNT1L                  =0x4C
TCNT1L_io               =0x2C  ; for IN/OUT
TCNT1H                  =0x4D
TCNT1H_io               =0x2D  ; for IN/OUT
TCCR1C                  =0x7A
FOC1A                   =7
FOC1B                   =6
FOC1C                   =5
TCCR1B                  =0x4E
TCCR1B_io               =0x2E  ; for IN/OUT
ICNC1                   =7
ICES1                   =6
WGM13                   =4
WGM12                   =3
CS12                    =2
CS11                    =1
CS10                    =0
TCCR1A                  =0x4F
TCCR1A_io               =0x2F  ; for IN/OUT
COM1A1                  =7
COM1A0                  =6
COM1B1                  =5
COM1B0                  =4
COM1C1                  =3
COM1C0                  =2
WGM11                   =1
WGM10                   =0
;
; Timer/Counter 0
ASSR                    =0x50
ASSR_io                 =0x30  ; for IN/OUT
AS0                     =3
TCN0UB                  =2
OCR0UB                  =1
TCR0UB                  =0
OCR0                    =0x51
OCR0_io                 =0x31  ; for IN/OUT
TCNT0                   =0x52
TCNT0_io                =0x32  ; for IN/OUT
TCCR0                   =0x53
TCCR0_io                =0x33  ; for IN/OUT
FOC0                    =7
WGM00                   =6
COM01                   =5
COM00                   =4
WGM01                   =3
CS02                    =2
CS01                    =1
CS00                    =0
;
; Oscillator Calibration Register
OSCCAL                  =0x6F
;
; MCU
MCUSR                   =0x54
MCUSR_io                =0x34  ; for IN/OUT
MCUCSR                  =0x54
MCUCSR_io               =0x34  ; for IN/OUT
JTD                     =7
JTRF                    =4
WDRF                    =3
BORF                    =2
EXTRF                   =1
PORF                    =0
MCUCR                   =0x55
MCUCR_io                =0x35  ; for IN/OUT
SRE                     =7
SRW10                   =6
SE                      =5
SM1                     =4
SM0                     =3
SM2                     =2
IVSEL                   =1
IVCE                    =0
;
; SPM Control and Status Register
SPMCSR                  =0x68
SPMIE                   =7
RWWSB                   =6
RWWSRE                  =4
BLBSET                  =3
PGWRT                   =2
PGERS                   =1
SPMEN                   =0
;
; Timer/Counter Interrupts
TIFR                    =0x56
TIFR_io                 =0x36  ; for IN/OUT
OCF2                    =7
TOV2                    =6
ICF1                    =5
OCF1A                   =4
OCF1B                   =3
TOV1                    =2
OCF0                    =1
TOV0                    =0
TIMSK                   =0x57
TIMSK_io                =0x37  ; for IN/OUT
OCIE2                   =7
TOIE2                   =6
TICIE1                  =5
OCIE1A                  =4
OCIE1B                  =3
TOIE1                   =2
OCIE0                   =1
TOIE0                   =0
ETIFR                   =0x7C
ICF3                    =5
OCF3A                   =4
OCF3B                   =3
TOV3                    =2
OCF3C                   =1
OCF1C                   =0
ETIMSK                  =0x7D
TICIE3                  =5
OCIE3A                  =4
OCIE3B                  =3
TOIE3                   =2
OCIE3C                  =1
OCIE1C                  =0
; Èxternal Interrupts 
EIFR                    =0x58
EIFR_io                 =0x38  ; for IN/OUT
INTF7                   =7
INTF6                   =6
INTF5                   =5
INTF4                   =4
INTF3                   =3
INTF2                   =2
INTF1                   =1
INTF0                   =0
EIMSK                   =0x59
EIMSK_io                =0x39  ; for IN/OUT
INT7                    =7
INT6                    =6
INT5                    =5
INT4                    =4
INT3                    =3
INT2                    =2
INT1                    =1
INT0                    =0
EICRB                   =0x5A
EICRB_io                =0x3A  ; for IN/OUT
ISC71                   =7
ISC70                   =6
ISC61                   =5
ISC60                   =4
ISC51                   =3
ISC50                   =2
ISC41                   =1
ISC40                   =0
EICRA                   =0x6A
ISC31                   =7
ISC30                   =6
ISC21                   =5
ISC20                   =4
ISC11                   =3
ISC10                   =2
ISC01                   =1
ISC00                   =0
;
; XDIV Divide control register
XDIV                    =0x5C
XDIV_io                 =0x3C  ; for IN/OUT
XDIVEN                  =7
;
; Stack Pointer
SP                      =0x5D
SP_io                   =0x3D  ; for IN/OUT
SPL                     =0x5D
SPL_io                  =0x3D  ; for IN/OUT
SPH                     =0x5E
SPH_io                  =0x3E  ; for IN/OUT
;
; Status REGister
SREG                    =0x5F
SREG_io                 =0x3F  ; for IN/OUT
;
; eXternal Memory Control Register
XMCRB                   =0x6C
XMBK                    =7
XMM2                    =2
XMM1                    =1
XMM0                    =0
XMCRA                   =0x6D
SRL2                    =6
SRL1                    =5
SRL0                    =4
SRW01                   =3
SRW00                   =2
SRW11                   =1
;
; Port A bits
PORTA7                  =7
PORTA6                  =6
PORTA5                  =5
PORTA4                  =4
PORTA3                  =3
PORTA2                  =2
PORTA1                  =1
PORTA0                  =0
PA7                     =7
PA6                     =6
PA5                     =5
PA4                     =4
PA3                     =3
PA2                     =2
PA1                     =1
PA0                     =0
DDA7                    =7
DDA6                    =6
DDA5                    =5
DDA4                    =4
DDA3                    =3
DDA2                    =2
DDA1                    =1
DDA0                    =0
PINA7                   =7
PINA6                   =6
PINA5                   =5
PINA4                   =4
PINA3                   =3
PINA2                   =2
PINA1                   =1
PINA0                   =0
;
; Port B bits
PORTB7                  =7
PORTB6                  =6
PORTB5                  =5
PORTB4                  =4
PORTB3                  =3
PORTB2                  =2
PORTB1                  =1
PORTB0                  =0
PB7                     =7
PB6                     =6
PB5                     =5
PB4                     =4
PB3                     =3
PB2                     =2
PB1                     =1
PB0                     =0
DDB7                    =7
DDB6                    =6
DDB5                    =5
DDB4                    =4
DDB3                    =3
DDB2                    =2
DDB1                    =1
DDB0                    =0
PINB7                   =7
PINB6                   =6
PINB5                   =5
PINB4                   =4
PINB3                   =3
PINB2                   =2
PINB1                   =1
PINB0                   =0
;
; Port C bits
PORTC7                  =7
PORTC6                  =6
PORTC5                  =5
PORTC4                  =4
PORTC3                  =3
PORTC2                  =2
PORTC1                  =1
PORTC0                  =0
PC7                     =7
PC6                     =6
PC5                     =5
PC4                     =4
PC3                     =3
PC2                     =2
PC1                     =1
PC0                     =0
DDC7                    =7
DDC6                    =6
DDC5                    =5
DDC4                    =4
DDC3                    =3
DDC2                    =2
DDC1                    =1
DDC0                    =0
PINC7                   =7
PINC6                   =6
PINC5                   =5
PINC4                   =4
PINC3                   =3
PINC2                   =2
PINC1                   =1
PINC0                   =0
;
; Port D bits
PORTD7                  =7
PORTD6                  =6
PORTD5                  =5
PORTD4                  =4
PORTD3                  =3
PORTD2                  =2
PORTD1                  =1
PORTD0                  =0
PD7                     =7
PD6                     =6
PD5                     =5
PD4                     =4
PD3                     =3
PD2                     =2
PD1                     =1
PD0                     =0
DDD7                    =7
DDD6                    =6
DDD5                    =5
DDD4                    =4
DDD3                    =3
DDD2                    =2
DDD1                    =1
DDD0                    =0
PIND7                   =7
PIND6                   =6
PIND5                   =5
PIND4                   =4
PIND3                   =3
PIND2                   =2
PIND1                   =1
PIND0                   =0
;
; Port E bits
PORTE7                  =7
PORTE6                  =6
PORTE5                  =5
PORTE4                  =4
PORTE3                  =3
PORTE2                  =2
PORTE1                  =1
PORTE0                  =0
PE7                     =7
PE6                     =6
PE5                     =5
PE4                     =4
PE3                     =3
PE2                     =2
PE1                     =1
PE0                     =0
DDE7                    =7
DDE6                    =6
DDE5                    =5
DDE4                    =4
DDE3                    =3
DDE2                    =2
DDE1                    =1
DDE0                    =0
PINE7                   =7
PINE6                   =6
PINE5                   =5
PINE4                   =4
PINE3                   =3
PINE2                   =2
PINE1                   =1
PINE0                   =0
;
; Port F bits
PORTF7                  =7
PORTF6                  =6
PORTF5                  =5
PORTF4                  =4
PORTF3                  =3
PORTF2                  =2
PORTF1                  =1
PORTF0                  =0
PF7                     =7
PF6                     =6
PF5                     =5
PF4                     =4
PF3                     =3
PF2                     =2
PF1                     =1
PF0                     =0
DDF7                    =7
DDF6                    =6
DDF5                    =5
DDF4                    =4
DDF3                    =3
DDF2                    =2
DDF1                    =1
DDF0                    =0
PINF7                   =7
PINF6                   =6
PINF5                   =5
PINF4                   =4
PINF3                   =3
PINF2                   =2
PINF1                   =1
PINF0                   =0
;
; Port G bits
PORTG4                  =4
PORTG3                  =3
PORTG2                  =2
PORTG1                  =1
PORTG0                  =0
PG4                     =4
PG3                     =3
PG2                     =2
PG1                     =1
PG0                     =0
DDG4                    =4
DDG3                    =3
DDG2                    =2
DDG1                    =1
DDG0                    =0
PING4                   =4
PING3                   =3
PING2                   =2
PING1                   =1
PING0                   =0
;
; Lock and Fuse Bits with LPM/SPM instructions
;
; lock bits
BLB12                   =5
BLB11                   =4
BLB02                   =3
BLB01                   =2
LB2                     =1
LB1                     =0
;
; fuses low bits
BODLEVEL                =7
BODEN                   =6
SUT1                    =5
SUT0                    =4
CKSEL3                  =3
CKSEL2                  =2
CKSEL1                  =1
CKSEL0                  =0
;
; fuses high bits
OCDEN                   =7
JTAGEN                  =6
SPIEN                   =5
CKOPT                   =4
EESAVE                  =3
BOOTSZ1                 =2
BOOTSZ0                 =1
BOOTRST                 =0
;
; extended fuses
M103C                   =1
WDTON                   =0
;
; ------------------------------------------------------------
;
; Interrupt Vector Macros
;
.macro set_vector_INT0
 .area vector (abs)
 .org  0x02
  rjmp @0
 .area text
.endmacro
.macro set_vector_EXT_INT0
 .area vector (abs)
 .org  0x02
  rjmp @0
 .area text
.endmacro
.macro set_vector_INT1
 .area vector (abs)
 .org  0x04
  rjmp @0
 .area text
.endmacro
.macro set_vector_EXT_INT1
 .area vector (abs)
 .org  0x04
  rjmp @0
 .area text
.endmacro
.macro set_vector_INT2
 .area vector (abs)
 .org  0x06
  rjmp @0
 .area text
.endmacro
.macro set_vector_EXT_INT2
 .area vector (abs)
 .org  0x06
  rjmp @0
 .area text
.endmacro
.macro set_vector_INT3
 .area vector (abs)
 .org  0x08
  rjmp @0
 .area text
.endmacro
.macro set_vector_EXT_INT3
 .area vector (abs)
 .org  0x08
  rjmp @0
 .area text
.endmacro
.macro set_vector_INT4
 .area vector (abs)
 .org  0x0A
  rjmp @0
 .area text
.endmacro
.macro set_vector_EXT_INT4
 .area vector (abs)
 .org  0x0A
  rjmp @0
 .area text
.endmacro
.macro set_vector_INT5
 .area vector (abs)
 .org  0x0C
  rjmp @0
 .area text
.endmacro
.macro set_vector_EXT_INT5
 .area vector (abs)
 .org  0x0C
  rjmp @0
 .area text
.endmacro
.macro set_vector_INT6
 .area vector (abs)
 .org  0x0E
  rjmp @0
 .area text
.endmacro
.macro set_vector_EXT_INT6
 .area vector (abs)
 .org  0x0E
  rjmp @0
 .area text
.endmacro
.macro set_vector_INT7
 .area vector (abs)
 .org  0x10
  rjmp @0
 .area text
.endmacro
.macro set_vector_EXT_INT7
 .area vector (abs)
 .org  0x10
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER2_COMPA
 .area vector (abs)
 .org  0x12
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER2_COMP
 .area vector (abs)
 .org  0x12
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM2_COMP
 .area vector (abs)
 .org  0x12
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER2_OVF
 .area vector (abs)
 .org  0x14
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM2_OVF
 .area vector (abs)
 .org  0x14
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER1_CAPT
 .area vector (abs)
 .org  0x16
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM1_CAPT
 .area vector (abs)
 .org  0x16
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER1_COMPA
 .area vector (abs)
 .org  0x18
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM1_COMPA
 .area vector (abs)
 .org  0x18
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER1_COMPB
 .area vector (abs)
 .org  0x1A
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM1_COMPB
 .area vector (abs)
 .org  0x1A
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER1_OVF
 .area vector (abs)
 .org  0x1C
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM1_OVF
 .area vector (abs)
 .org  0x1C
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER0_COMPA
 .area vector (abs)
 .org  0x1E
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER0_COMP
 .area vector (abs)
 .org  0x1E
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM0_COMP
 .area vector (abs)
 .org  0x1E
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER0_OVF
 .area vector (abs)
 .org  0x20
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM0_OVF
 .area vector (abs)
 .org  0x20
  rjmp @0
 .area text
.endmacro
.macro set_vector_SPI_STC
 .area vector (abs)
 .org  0x22
  rjmp @0
 .area text
.endmacro
.macro set_vector_USART0_RX
 .area vector (abs)
 .org  0x24
  rjmp @0
 .area text
.endmacro
.macro set_vector_USART0_RXC
 .area vector (abs)
 .org  0x24
  rjmp @0
 .area text
.endmacro
.macro set_vector_USART0_DRE
 .area vector (abs)
 .org  0x26
  rjmp @0
 .area text
.endmacro
.macro set_vector_USART0_UDRE
 .area vector (abs)
 .org  0x26
  rjmp @0
 .area text
.endmacro
.macro set_vector_USART0_TX
 .area vector (abs)
 .org  0x28
  rjmp @0
 .area text
.endmacro
.macro set_vector_USART0_TXC
 .area vector (abs)
 .org  0x28
  rjmp @0
 .area text
.endmacro
.macro set_vector_ADC
 .area vector (abs)
 .org  0x2A
  rjmp @0
 .area text
.endmacro
.macro set_vector_EE_RDY
 .area vector (abs)
 .org  0x2C
  rjmp @0
 .area text
.endmacro
.macro set_vector_EE_READY
 .area vector (abs)
 .org  0x2C
  rjmp @0
 .area text
.endmacro
.macro set_vector_ANA_COMP
 .area vector (abs)
 .org  0x2E
  rjmp @0
 .area text
.endmacro
.macro set_vector_ANALOG_COMP
 .area vector (abs)
 .org  0x2E
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER1_COMPC
 .area vector (abs)
 .org  0x30
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM1_COMPC
 .area vector (abs)
 .org  0x30
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER3_CAPT
 .area vector (abs)
 .org  0x32
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM3_CAPT
 .area vector (abs)
 .org  0x32
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER3_COMPA
 .area vector (abs)
 .org  0x34
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM3_COMPA
 .area vector (abs)
 .org  0x34
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER3_COMPB
 .area vector (abs)
 .org  0x36
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM3_COMPB
 .area vector (abs)
 .org  0x36
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER3_COMPC
 .area vector (abs)
 .org  0x38
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM3_COMPC
 .area vector (abs)
 .org  0x38
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER3_OVF
 .area vector (abs)
 .org  0x3A
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM3_OVF
 .area vector (abs)
 .org  0x3A
  rjmp @0
 .area text
.endmacro
.macro set_vector_USART1_RX
 .area vector (abs)
 .org  0x3C
  rjmp @0
 .area text
.endmacro
.macro set_vector_USART1_RXC
 .area vector (abs)
 .org  0x3C
  rjmp @0
 .area text
.endmacro
.macro set_vector_USART1_DRE
 .area vector (abs)
 .org  0x3E
  rjmp @0
 .area text
.endmacro
.macro set_vector_USART1_UDRE
 .area vector (abs)
 .org  0x3E
  rjmp @0
 .area text
.endmacro
.macro set_vector_USART1_TX
 .area vector (abs)
 .org  0x40
  rjmp @0
 .area text
.endmacro
.macro set_vector_USART1_TXC
 .area vector (abs)
 .org  0x40
  rjmp @0
 .area text
.endmacro
.macro set_vector_TWI
 .area vector (abs)
 .org  0x42
  rjmp @0
 .area text
.endmacro
.macro set_vector_TWSI
 .area vector (abs)
 .org  0x42
  rjmp @0
 .area text
.endmacro
.macro set_vector_SPM_RDY
 .area vector (abs)
 .org  0x44
  rjmp @0
 .area text
.endmacro
.macro set_vector_SPM_READY
 .area vector (abs)
 .org  0x44
  rjmp @0
 .area text
.endmacro
;------
;<eof>
