; iccavr asm header file for t10
; generated by maschag 0.8.7 on 04-28-2009
;-------------------------------------------------------------
;
; Memory info
FLASHEND                =0x03FF
E2END                   =0 ; Part has no EEPROM
RAMSTART                =0x0040
RAMEND                  =0x005F
XRAMEND                 =0 ; Part has no external RAM interface
;
;-------------------------------------------------------------
;
; IO registers
;
; Port B
PINB                    =0
DDRB                    =1
PORTB                   =2
PUEB                    =3
PORTCR                  =12
DIDR0                   =23
;
; Pin Interrupts
PCMSK                   =16
PCIFR                   =17
PCICR                   =18
EIMSK                   =19
EIFR                    =20
EICRA                   =21
;
; ADC
ADC                     =25
ADCL                    =25
ADMUX                   =27
ADCMUX                  =27
ADCSRB                  =28
ADCSRA                  =29
;
; Analog Comp
ACSR                    =31
;
; Timer/Counter 0
ICR0                    =0x02
ICR0L                   =0x02
ICR0H                   =0x03
OCR0A                   =0x06
OCR0AL                  =0x06
OCR0AH                  =0x07
OCR0B                   =0x04
OCR0BL                  =0x04
OCR0BH                  =0x05
TCNT0                   =0x08
TCNT0L                  =0x08
TCNT0H                  =0x09
TCCR0A                  =0x0E
TCCR0B                  =0x0D
TCCR0C                  =0x0C
;
; Timer/Counter Interrupts
TIFR0                   =0x0A
TIFR                    =0x0A
TIMSK0                  =0x0B
TIMSK                   =0x0B
;
; General Control
GTCCR                   =0x0F
;
; Watchdog Timer Control
WDTCR                   =0x11
;
; NVM
NVMCSR                  =0x12
NVMCMD                  =0x13
;
; VLM
VLMCSR                  =0x14
;
; Power Reduction
PRR                     =0x15
;
; Clock Control
CLKPSR                  =0x16
CLKMSR                  =0x17
;
; RC oscillator
OSCCAL                  =0x19
;
; MCU
SMCR                    =0x1A
RSTFLR                  =0x1B
CCP                     =0x1C
;
; Stack Pointer
SP                      =0x1D
SPL                     =0x1D
;
; Status REGister
SREG                    =0x3F
;
; non-IO addresses
NVMLOCKBITS             =0x3F00  ; memory mapped, for LD/ST
CONFIGURATIONBITS       =0x3F40  ; memory mapped, for LD/ST
FLASHPROGRAMMEMORY      =0x4000  ; memory mapped, for LD/ST
;
; IO bits
;
; Port B bits
PUEB3                   =3
PUEB2                   =2
PUEB1                   =1
PUEB0                   =0
PORTB3                  =3
PORTB2                  =2
PORTB1                  =1
PORTB0                  =0
PB3                     =3
PB2                     =2
PB1                     =1
PB0                     =0
DDB3                    =3
DDB2                    =2
DDB1                    =1
DDB0                    =0
PINB3                   =3
PINB2                   =2
PINB1                   =1
PINB0                   =0
BBMB                    =1
PCINT3                  =3
PCINT2                  =2
PCINT1                  =1
PCINT0                  =0
ADC3D                   =3
ADC2D                   =2
ADC1D                   =1
ADC0D                   =0
;
; Pin Interrupt bits
ISC00                   =0
ISC01                   =1
INT0                    =0
INTF0                   =0
PCIE0                   =0
PCIF0                   =0
;
; Analog Digital Converter bits
MUX1                    =1
MUX0                    =0
ADEN                    =7
ADSC                    =6
ADATE                   =5
ADFR                    =5
ADIF                    =4
ADIE                    =3
ADPS2                   =2
ADPS1                   =1
ADPS0                   =0
ADTS2                   =2
ADTS1                   =1
ADTS0                   =0
;
; Analog Comparator bits
ACD                     =7
ACO                     =5
ACI                     =4
ACIE                    =3
ACIC                    =2
ACIS1                   =1
ACIS0                   =0
;
; Timer/Counter Interrupt bits
ICIE0                   =5
OCIE0A                  =1
OCIE0B                  =2
TOIE0                   =0
ICF0                    =5
OCF0A                   =1
OCF0B                   =2
TOV0                    =0
;
; Timer/Counter 0 Control bits
FOC0A                   =7
FOC0B                   =6
ICNC0                   =7
ICES0                   =6
WGM03                   =4
WGM02                   =3
CS02                    =2
CS01                    =1
CS00                    =0
COM0A1                  =7
COM0A0                  =6
COM0B1                  =5
COM0B0                  =4
WGM01                   =1
WGM00                   =0
;
; GTCCR bits
TSM                     =7
PSR10                   =0
;
; Watchdog Timer Control bits
WDIF                    =7
WDTIF                   =7
WDIE                    =6
WDTIE                   =6
WDP3                    =5
WDE                     =3
WDP2                    =2
WDP1                    =1
WDP0                    =0
;
; NVM bits
NVMBSY                  =7
;
; VLM bits
VLMF                    =7
VLMIE                   =6
VLM2                    =2
VLM1                    =1
VLM0                    =0
;
; PRR bits
PRADC                   =1
PRTIM0                  =0
;
; CLK Control bits
CLKPS3                  =3
CLKPS2                  =2
CLKPS1                  =1
CLKPS0                  =0
CLKMS1                  =1
CLKMS0                  =0
;
; Sleep Mode Control bits
SM2                     =3
SM1                     =2
SM0                     =1
SE                      =0
;
; Reset Flag bits
WDRF                    =3
EXTRF                   =1
PORF                    =0
;
; Lock and Config Fuses bits
;
; lock bits
NVLB2                   =1
LB2                     =1
NVLB1                   =0
LB1                     =0
;
; config bits
CKOUT                   =2
WDTON                   =1
RSTDISBL                =0
;
; ------------------------------------------------------------
;
; Interrupt Vector Macros
;
.macro set_vector_INT0
 .area vector (abs)
 .org  0x02
  rjmp @0
 .area text
.endmacro
.macro set_vector_PCINT0
 .area vector (abs)
 .org  0x04
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM0_CAPT
 .area vector (abs)
 .org  0x06
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM0_OVF
 .area vector (abs)
 .org  0x08
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM0_COMPA
 .area vector (abs)
 .org  0x0A
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM0_COMPB
 .area vector (abs)
 .org  0x0C
  rjmp @0
 .area text
.endmacro
.macro set_vector_ANA_COMP
 .area vector (abs)
 .org  0x0E
  rjmp @0
 .area text
.endmacro
.macro set_vector_WDT
 .area vector (abs)
 .org  0x10
  rjmp @0
 .area text
.endmacro
.macro set_vector_VLM
 .area vector (abs)
 .org  0x12
  rjmp @0
 .area text
.endmacro
.macro set_vector_ADC
 .area vector (abs)
 .org  0x14
  rjmp @0
 .area text
.endmacro
;------
;<eof>
