; iccavr asm header file for t461
; generated by maschag 0.8.7 on 04-15-2009
;-------------------------------------------------------------
;
; Memory info
FLASHEND                =0x0FFF
E2END                   =0x00FF
RAMSTART                =0x0060
RAMEND                  =0x015F
XRAMEND                 =0 ; Part has no external RAM interface
;
;-------------------------------------------------------------
;
; DIDR
DIDR0                   =0x01
DIDR1                   =0x02
;
; ADC
ADCSRB                  =0x03
ADC                     =0x04
ADCL                    =0x04
ADCH                    =0x05
ADCSRA                  =0x06
ADMUX                   =0x07
;
; Analog Comp
ACSRA                   =0x08
ACSRB                   =0x09
;
; GPIO
GPIO0                   =0x0A
GPIO1                   =0x0B
GPIO2                   =0x0C
;
; Universal Serial Interface
USICR                   =0x0D
USISR                   =0x0E
USIDR                   =0x0F
USIBR                   =0x10
USIPP                   =0x11
;
; Timer/Counter 0
OCR0B                   =0x12
OCR0A                   =0x13
TCNT0H                  =0x14
TCNT0L                  =0x32
TCCR0A                  =0x15
TCCR0B                  =0x33
;
; Port B
PINB                    =0x16
DDRB                    =0x17
PORTB                   =0x18
;
; Port A
PINA                    =0x19
DDRA                    =0x1A
PORTA                   =0x1B
;
; EEPROM
EECR                    =0x1C
EEDR                    =0x1D
EEAR                    =0x1E
EEARL                   =0x1E
;
; DWDR
DWDR                    =0x20
;
; Watchdog Timer Control Register
WDTCR                   =0x21
;
; PCMSK
PCMSK1                  =0x22
PCMSK0                  =0x23
;
; Timer/Counter 1
DT1                     =0x24
TC1H                    =0x25
; #define TCNT1H	(*(volatile unsigned char *)0x45) 
TCNT1                   =0x2E
; #define TCNT1L	(*(volatile unsigned char *)0x4E) 
TCCR1E                  =0x00
TCCR1D                  =0x26
TCCR1C                  =0x27
OCR1D                   =0x2A
OCR1C                   =0x2B
OCR1B                   =0x2C
OCR1A                   =0x2D
TCCR1B                  =0x2F
TCCR1A                  =0x30
;
; CLKPR
CLKPR                   =0x28
;
; PLL
PLLCSR                  =0x29
;
; RC oscillator
OSCCAL                  =0x31
;
; MCU
MCUSR                   =0x34
MCUCR                   =0x35
;
; PRR
PRR                     =0x36
;
; SPM
SPMCSR                  =0x37
;
; Timer/Counter Interrupts
TIFR                    =0x38
TIMSK                   =0x39
;
; General Interrupts
GIFR                    =0x3A
GIMSK                   =0x3B
;
; Stack Pointer
SP                      =0x3D
SPL                     =0x3D
SPH                     =0x3E
;
; Status REGister
SREG                    =0x3F
;
; General Interrupt registers
INT1                    =7
INT0                    =6
PCIE1                   =5
PCIE0                   =4
INTF1                   =7
INTF0                   =6
PCIF                    =5
;
; Timer/Counter Interrupt registers
OCIE1D                  =7
OCIE1A                  =6
OCIE1B                  =5
OCIE0A                  =4
OCIE0B                  =3
TOIE1                   =2
TOIE0                   =1
TICIE0                  =0
OCF1D                   =7
OCF1A                   =6
OCF1B                   =5
OCF0A                   =4
OCF0B                   =3
TOV1                    =2
TOV0                    =1
ICF0                    =0
;
; SPM Control Status Register
CTPB                    =4
RFLB                    =3
PGWRT                   =2
PGERS                   =1
SPMEN                   =0
;
; PRR
PRTIM1                  =3
PRTIM0                  =2
PRUSI                   =1
PRADC                   =0
;
; MCU general Control Register
PUD                     =6
SE                      =5
SM1                     =4
SM0                     =3
ISC01                   =1
ISC00                   =0
;
; MCU general Status Register
WDRF                    =3
BORF                    =2
EXTRF                   =1
PORF                    =0
;
; Timer/Counter 0 Control Register
TSM                     =4
TSM0                    =4
PSR0                    =3
CS02                    =2
CS01                    =1
CS00                    =0
TCW0                    =7
ICEN0                   =6
ICNC0                   =5
ICES0                   =4
ACIC0                   =3
WGM00                   =0
;
; Timer/Counter 1 Control Registers
COM1A1                  =7
COM1A0                  =6
COM1B1                  =5
COM1B0                  =4
FOC1A                   =3
FOC1B                   =2
PWM1A                   =1
PWM1B                   =0
PWM1X                   =7
; #define    CTC1     7 
PSR1                    =6
DTPS11                  =5
DTPS10                  =4
CS13                    =3
CS12                    =2
CS11                    =1
CS10                    =0
COM1A1S                 =7
COM1A0S                 =6
COM1B1S                 =5
COM1B0S                 =4
COM1D1                  =3
COM1D0                  =2
FOC1D                   =1
PWM1D                   =0
FPIE1                   =7
FPEN1                   =6
FPNC1                   =5
FPES1                   =4
FPAC1                   =3
FPF1                    =2
WGM11                   =1
WGM10                   =0
OC1OE5                  =5
OC1OE4                  =4
OC1OE3                  =3
OC1OE2                  =2
OC1OE1                  =1
OC1OE0                  =0
;
; PLLCSR
LSM                     =7
PCKE                    =2
PLLE                    =1
PLOCK                   =0
;
; CLKPR
CLKPCE                  =7
CLKPS3                  =3
CLKPS2                  =2
CLKPS1                  =1
CLKPS0                  =0
;
; TC1H
; #define    TC19     1 
; #define    TC18     0 
;
; DT1
DT1H3                   =7
DT1H2                   =6
DT1H1                   =5
DT1H0                   =4
DT1L3                   =3
DT1L2                   =2
DT1L1                   =1
DT1L0                   =0
;
; PCMSK
PCINT15                 =7
PCINT14                 =6
PCINT13                 =5
PCINT12                 =4
PCINT11                 =3
PCINT10                 =2
PCINT9                  =1
PCINT8                  =0
PCINT7                  =7
PCINT6                  =6
PCINT5                  =5
PCINT4                  =4
PCINT3                  =3
PCINT2                  =2
PCINT1                  =1
PCINT0                  =0
;
; Watchdog Timer Control Register
WDIF                    =7
WDIE                    =6
WDP3                    =5
WDCE                    =4
WDE                     =3
WDP2                    =2
WDP1                    =1
WDP0                    =0
;
; EEPROM Control Register
EEPM1                   =5
EEPM0                   =4
EERIE                   =3
EEMPE                   =2
EEMWE                   =2
EEPE                    =1
EEWE                    =1
EERE                    =0
;
; Port A bits
PORTA7                  =7
PORTA6                  =6
PORTA5                  =5
PORTA4                  =4
PORTA3                  =3
PORTA2                  =2
PORTA1                  =1
PORTA0                  =0
PA7                     =7
PA6                     =6
PA5                     =5
PA4                     =4
PA3                     =3
PA2                     =2
PA1                     =1
PA0                     =0
DDA7                    =7
DDA6                    =6
DDA5                    =5
DDA4                    =4
DDA3                    =3
DDA2                    =2
DDA1                    =1
DDA0                    =0
PINA7                   =7
PINA6                   =6
PINA5                   =5
PINA4                   =4
PINA3                   =3
PINA2                   =2
PINA1                   =1
PINA0                   =0
;
; Port B bits
PORTB7                  =7
PORTB6                  =6
PORTB5                  =5
PORTB4                  =4
PORTB3                  =3
PORTB2                  =2
PORTB1                  =1
PORTB0                  =0
PB7                     =7
PB6                     =6
PB5                     =5
PB4                     =4
PB3                     =3
PB2                     =2
PB1                     =1
PB0                     =0
DDB7                    =7
DDB6                    =6
DDB5                    =5
DDB4                    =4
DDB3                    =3
DDB2                    =2
DDB1                    =1
DDB0                    =0
PINB7                   =7
PINB6                   =6
PINB5                   =5
PINB4                   =4
PINB3                   =3
PINB2                   =2
PINB1                   =1
PINB0                   =0
;
; Universal Serial Interface
USIPOS                  =0
USISIF                  =7
USIOIF                  =6
USIPF                   =5
USIDC                   =4
USICNT3                 =3
USICNT2                 =2
USICNT1                 =1
USICNT0                 =0
USISIE                  =7
USIOIE                  =6
USIWM1                  =5
USIWM0                  =4
USICS1                  =3
USICS0                  =2
USICLK                  =1
USITC                   =0
;
; Analog Comparator Control and Status Register
HSEL                    =7
HLEV                    =6
ACM2                    =2
ACM1                    =1
ACM0                    =0
ACD                     =7
ACBG                    =6
ACO                     =5
ACI                     =4
ACIE                    =3
ACME                    =2
ACIS1                   =1
ACIS0                   =0
;
; Analog Digital Converter MUX Register
REFS1                   =7
REFS0                   =6
ADLAR                   =5
MUX4                    =4
MUX3                    =3
MUX2                    =2
MUX1                    =1
MUX0                    =0
;
; Analog Digital Converter Control/Status Register
ADEN                    =7
ADSC                    =6
ADATE                   =5
ADIF                    =4
ADIE                    =3
ADPS2                   =2
ADPS1                   =1
ADPS0                   =0
BIN                     =7
GSEL                    =6
REFS2                   =4
MUX5                    =3
ADTS2                   =2
ADTS1                   =1
ADTS0                   =0
;
; DIDR
ADC10D                  =7
ADC9D                   =6
ADC8D                   =5
ADC7D                   =4
ADC6D                   =7
ADC5D                   =6
ADC4D                   =5
ADC3D                   =4
ADC2D                   =2
ADC1D                   =1
ADC0D                   =0
AREFD                   =3
;
; Lock and Fuse Bits with LPM/SPM instructions
;
; lock bits
LB2                     =1
LB1                     =0
;
; fuses low bits
CKDIV8                  =7
CKOUT                   =6
SUT1                    =5
SUT0                    =4
CKSEL3                  =3
CKSEL2                  =2
CKSEL1                  =1
CKSEL0                  =0
;
; fuses high bits
RSTDISBL                =7
DWEN                    =6
SPIEN                   =5
WDTON                   =4
EESAVE                  =3
BODLEVEL2               =2
BODLEVEL1               =1
BODLEVEL0               =0
;
; fuses extended bits
SELFPRGEN               =0
;
; ------------------------------------------------------------
;
; Interrupt Vector Macros
;
.macro set_vector_INT0
 .area vector (abs)
 .org  0x02
  rjmp @0
 .area text
.endmacro
.macro set_vector_EXT_INT0
 .area vector (abs)
 .org  0x02
  rjmp @0
 .area text
.endmacro
.macro set_vector_PCINT
 .area vector (abs)
 .org  0x04
  rjmp @0
 .area text
.endmacro
.macro set_vector_PCINT0
 .area vector (abs)
 .org  0x04
  rjmp @0
 .area text
.endmacro
.macro set_vector_IO_PINS
 .area vector (abs)
 .org  0x04
  rjmp @0
 .area text
.endmacro
.macro set_vector_PIN_CHANGE
 .area vector (abs)
 .org  0x04
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM1_COMPA
 .area vector (abs)
 .org  0x06
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM1_CMP1A
 .area vector (abs)
 .org  0x06
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER1_CMPA
 .area vector (abs)
 .org  0x06
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER1_COMPA
 .area vector (abs)
 .org  0x06
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM1_COMPB
 .area vector (abs)
 .org  0x08
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM1_CMP1B
 .area vector (abs)
 .org  0x08
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER1_CMPB
 .area vector (abs)
 .org  0x08
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER1_COMPB
 .area vector (abs)
 .org  0x08
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM1_OVF
 .area vector (abs)
 .org  0x0A
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER1_OVF1
 .area vector (abs)
 .org  0x0A
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER1_OVF
 .area vector (abs)
 .org  0x0A
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM0_OVF
 .area vector (abs)
 .org  0x0C
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER0_OVF0
 .area vector (abs)
 .org  0x0C
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER0_OVF
 .area vector (abs)
 .org  0x0C
  rjmp @0
 .area text
.endmacro
.macro set_vector_USI_STRT
 .area vector (abs)
 .org  0x0E
  rjmp @0
 .area text
.endmacro
.macro set_vector_USI_START
 .area vector (abs)
 .org  0x0E
  rjmp @0
 .area text
.endmacro
.macro set_vector_USI_OVF
 .area vector (abs)
 .org  0x10
  rjmp @0
 .area text
.endmacro
.macro set_vector_EE_RDY
 .area vector (abs)
 .org  0x12
  rjmp @0
 .area text
.endmacro
.macro set_vector_ANA_COMP
 .area vector (abs)
 .org  0x14
  rjmp @0
 .area text
.endmacro
.macro set_vector_ADC
 .area vector (abs)
 .org  0x16
  rjmp @0
 .area text
.endmacro
.macro set_vector_WDT
 .area vector (abs)
 .org  0x18
  rjmp @0
 .area text
.endmacro
.macro set_vector_INT1
 .area vector (abs)
 .org  0x1A
  rjmp @0
 .area text
.endmacro
.macro set_vector_EXT_INT1
 .area vector (abs)
 .org  0x1A
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM0_COMPA
 .area vector (abs)
 .org  0x1C
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER0_COMPA
 .area vector (abs)
 .org  0x1C
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM0_COMPB
 .area vector (abs)
 .org  0x1E
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER0_COMPB
 .area vector (abs)
 .org  0x1E
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM0_CAPT
 .area vector (abs)
 .org  0x20
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER0_CAPT
 .area vector (abs)
 .org  0x20
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM1_COMPD
 .area vector (abs)
 .org  0x22
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER1_COMPD
 .area vector (abs)
 .org  0x22
  rjmp @0
 .area text
.endmacro
.macro set_vector_FAULT_PROTECTION
 .area vector (abs)
 .org  0x24
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM1_FAULT_PROTECTION
 .area vector (abs)
 .org  0x24
  rjmp @0
 .area text
.endmacro
;------
;<eof>
