; iccavr asm header file for t25
; generated by maschag 0.8.7 on 04-15-2009
;-------------------------------------------------------------
;
; Memory info
FLASHEND                =0x07FF
E2END                   =0x007F
RAMSTART                =0x0060
RAMEND                  =0x00DF
XRAMEND                 =0 ; Part has no external RAM interface
;
;-------------------------------------------------------------
;
; ADC
ADCSRB                  =0x03
ADC                     =0x04
ADCL                    =0x04
ADCH                    =0x05
ADCSRA                  =0x06
ADMUX                   =0x07
;
; Analog Comp
ACSR                    =0x08
;
; Universal Serial Interface
USICR                   =0x0D
USISR                   =0x0E
USIDR                   =0x0F
USIBR                   =0x10
;
; GPIO
GPIOR0                  =0x11
GPIOR1                  =0x12
GPIOR2                  =0x13
;
; DIDR
DIDR0                   =0x14
;
; PCMSK
PCMSK                   =0x15
;
; Port B
PINB                    =0x16
DDRB                    =0x17
PORTB                   =0x18
;
; EEPROM
EECR                    =0x1C
EEDR                    =0x1D
EEAR                    =0x1E
EEARL                   =0x1E
;
; PRR
PRR                     =0x20
;
; Watchdog Timer Control Register
WDTCR                   =0x21
;
; DWD Register
DWDR                    =0x22
;
; DT..
DTPS1                   =0x23
DTPS                    =0x23
DT1B                    =0x24
; #define DTVALB	(*(volatile unsigned char *)0x44)
DT1A                    =0x25
; #define DTVALA	(*(volatile unsigned char *)0x45)
;
; CLK + PLL
CLKPR                   =0x26
PLLCSR                  =0x27
;
; Timer/Counter 0, part 1
OCR0B                   =0x28
OCR0A                   =0x29
TCCR0A                  =0x2A
;
; Timer/Counter 1
OCR1B                   =0x2B
GTCCR                   =0x2C
OCR1C                   =0x2D
OCR1A                   =0x2E
TCNT1                   =0x2F
TCCR1                   =0x30
TCCR1A                  =0x30
;
; RC oscillator
OSCCAL                  =0x31
;
; Timer/Counter 0, part 2
TCNT0                   =0x32
TCCR0B                  =0x33
;
; MCU
MCUSR                   =0x34
MCUCR                   =0x35
;
; SPM
SPMCSR                  =0x37
;
; Timer/Counter Interrupts
TIFR                    =0x38
TIMSK                   =0x39
;
; General Interrupts
GIFR                    =0x3A
GIMSK                   =0x3B
;
; Stack Pointer
SP                      =0x3D
SPL                     =0x3D
;
; Status REGister
SREG                    =0x3F
;
; General Interrupt registers
INT0                    =6
PCIE                    =5
INTF0                   =6
PCIF                    =5
;
; Timer/Counter Interrupt registers
OCIE1A                  =6
OCIE1B                  =5
OCIE0A                  =4
OCIE0B                  =3
TOIE1                   =2
TOIE0                   =1
OCF1A                   =6
OCF1B                   =5
OCF0A                   =4
OCF0B                   =3
TOV1                    =2
TOV0                    =1
;
; SPM Control Status Register
RSIG                    =5
CTPB                    =4
RFLB                    =3
PGWRT                   =2
PGERS                   =1
SPMEN                   =0
;
; MCU general Control Register
BODS                    =7
PUD                     =6
SE                      =5
SM1                     =4
SM0                     =3
BODSE                   =2
ISC01                   =1
ISC00                   =0
;
; MCU general Status Register
WDRF                    =3
BORF                    =2
EXTRF                   =1
PORF                    =0
;
; Timer/Counter 0 Control Register
FOC0A                   =7
FOC0B                   =6
WGM02                   =3
CS02                    =2
CS01                    =1
CS00                    =0
COM0A1                  =7
COM0A0                  =6
COM0B1                  =5
COM0B0                  =4
WGM01                   =1
WGM00                   =0
;
; Timer/Counter 1 Control Registers
CTC1                    =7
PWM1A                   =6
COM1A1                  =5
COM1A0                  =4
CS13                    =3
CS12                    =2
CS11                    =1
CS10                    =0
;
; GTCCR
TSM                     =7
PWM1B                   =6
COM1B1                  =5
COM1B0                  =4
FOC1B                   =3
FOC1A                   =2
PSR1                    =1
PSR0                    =0
;
; PLLCSR
LSM                     =7
PCKE                    =2
PLLE                    =1
PLOCK                   =0
;
; CLKPR
CLKPCE                  =7
CLKPS3                  =3
CLKPS2                  =2
CLKPS1                  =1
CLKPS0                  =0
;
; DT1A
DT1AH3                  =7
DT1AH2                  =6
DT1AH1                  =5
DT1AH0                  =4
DT1AL3                  =3
DT1AL2                  =2
DT1AL1                  =1
DT1AL0                  =0
;
; DT1B
DT1BH3                  =7
DT1BH2                  =6
DT1BH1                  =5
DT1BH0                  =4
DT1BL3                  =3
DT1BL2                  =2
DT1BL1                  =1
DT1BL0                  =0
;
; DTPS
DTPS11                  =1
DTPS10                  =0
;
; Watchdog Timer Control Register
WDIF                    =7
WDTIF                   =7
WDIE                    =6
WDTIE                   =6
WDP3                    =5
WDCE                    =4
WDE                     =3
WDP2                    =2
WDP1                    =1
WDP0                    =0
;
; PRR
PRTIM1                  =3
PRTIM0                  =2
PRUSI                   =1
PRADC                   =0
;
; EEPROM Control Register
EEPM1                   =5
EEPM0                   =4
EERIE                   =3
EEMPE                   =2
EEMWE                   =2
EEPE                    =1
EEWE                    =1
EERE                    =0
;
; Port B bits
PORTB5                  =5
PORTB4                  =4
PORTB3                  =3
PORTB2                  =2
PORTB1                  =1
PORTB0                  =0
PB5                     =5
PB4                     =4
PB3                     =3
PB2                     =2
PB1                     =1
PB0                     =0
DDB5                    =5
DDB4                    =4
DDB3                    =3
DDB2                    =2
DDB1                    =1
DDB0                    =0
PINB5                   =5
PINB4                   =4
PINB3                   =3
PINB2                   =2
PINB1                   =1
PINB0                   =0
;
; PCMSK
PCINT5                  =5
PCINT4                  =4
PCINT3                  =3
PCINT2                  =2
PCINT1                  =1
PCINT0                  =0
;
; DIDR
ADC0D                   =5
ADC2D                   =4
ADC3D                   =3
ADC1D                   =2
AIN1D                   =1
AIN0D                   =0
;
; Universal Serial Interface
USISIF                  =7
USIOIF                  =6
USIPF                   =5
USIDC                   =4
USICNT3                 =3
USICNT2                 =2
USICNT1                 =1
USICNT0                 =0
USISIE                  =7
USIOIE                  =6
USIWM1                  =5
USIWM0                  =4
USICS1                  =3
USICS0                  =2
USICLK                  =1
USITC                   =0
;
; Analog Comparator Control and Status Register
ACD                     =7
ACBG                    =6
ACO                     =5
ACI                     =4
ACIE                    =3
ACIS1                   =1
ACIS0                   =0
;
; Analog Digital Converter
REFS1                   =7
REFS0                   =6
ADLAR                   =5
REFS2                   =4
MUX3                    =3
MUX2                    =2
MUX1                    =1
MUX0                    =0
ADEN                    =7
ADSC                    =6
ADATE                   =5
ADIF                    =4
ADIE                    =3
ADPS2                   =2
ADPS1                   =1
ADPS0                   =0
BIN                     =7
ACME                    =6
IPR                     =5
ADTS2                   =2
ADTS1                   =1
ADTS0                   =0
;
; Lock and Fuse Bits with LPM/SPM instructions
;
; lock bits
LB2                     =1
LB1                     =0
;
; fuses low bits
CKDIV8                  =7
CKOUT                   =6
SUT1                    =5
SUT0                    =4
CKSEL3                  =3
CKSEL2                  =2
CKSEL1                  =1
CKSEL0                  =0
;
; fuses high bits
RSTDISBL                =7
DWEN                    =6
SPIEN                   =5
WDTON                   =4
EESAVE                  =3
BODLEVEL2               =2
BODLEVEL1               =1
BODLEVEL0               =0
;
; fuses extended bits
SELFPRGEN               =0
;
; ------------------------------------------------------------
;
; Interrupt Vector Macros
;
.macro set_vector_INT0
 .area vector (abs)
 .org  0x02
  rjmp @0
 .area text
.endmacro
.macro set_vector_EXT_INT0
 .area vector (abs)
 .org  0x02
  rjmp @0
 .area text
.endmacro
.macro set_vector_PCINT0
 .area vector (abs)
 .org  0x04
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM1_COMPA
 .area vector (abs)
 .org  0x06
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER1_COMPA
 .area vector (abs)
 .org  0x06
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM1_OVF
 .area vector (abs)
 .org  0x08
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER1_OVF
 .area vector (abs)
 .org  0x08
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM0_OVF
 .area vector (abs)
 .org  0x0A
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER0_OVF
 .area vector (abs)
 .org  0x0A
  rjmp @0
 .area text
.endmacro
.macro set_vector_EE_RDY
 .area vector (abs)
 .org  0x0C
  rjmp @0
 .area text
.endmacro
.macro set_vector_ANA_COMP
 .area vector (abs)
 .org  0x0E
  rjmp @0
 .area text
.endmacro
.macro set_vector_ADC
 .area vector (abs)
 .org  0x10
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM1_COMPB
 .area vector (abs)
 .org  0x12
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER1_COMPB
 .area vector (abs)
 .org  0x12
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM0_COMPA
 .area vector (abs)
 .org  0x14
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER0_COMPA
 .area vector (abs)
 .org  0x14
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIM0_COMPB
 .area vector (abs)
 .org  0x16
  rjmp @0
 .area text
.endmacro
.macro set_vector_TIMER0_COMPB
 .area vector (abs)
 .org  0x16
  rjmp @0
 .area text
.endmacro
.macro set_vector_WDT
 .area vector (abs)
 .org  0x18
  rjmp @0
 .area text
.endmacro
.macro set_vector_USI_START
 .area vector (abs)
 .org  0x1A
  rjmp @0
 .area text
.endmacro
.macro set_vector_USI_STRT
 .area vector (abs)
 .org  0x1A
  rjmp @0
 .area text
.endmacro
.macro set_vector_USI_OVF
 .area vector (abs)
 .org  0x1C
  rjmp @0
 .area text
.endmacro
;------
;<eof>
