; iccavr asm header file for USB1287
; generated by maschag 0.8.7 on 04-15-2009
;-------------------------------------------------------------
;
; Memory info
FLASHEND                =0x1FFFF
E2END                   =0x0FFF
RAMSTART                =0x0100
RAMEND                  =0x20FF
XRAMEND                 =0xFFFF
;
;-------------------------------------------------------------
;
; Port F
PINF                    =0x0F  ; for IN/OUT, CBI/SBI, SBIC/SBIS
DDRF                    =0x10  ; for IN/OUT, CBI/SBI, SBIC/SBIS
PORTF                   =0x11  ; for IN/OUT, CBI/SBI, SBIC/SBIS
;
; Port E
PINE                    =0x0C  ; for IN/OUT, CBI/SBI, SBIC/SBIS
DDRE                    =0x0D  ; for IN/OUT, CBI/SBI, SBIC/SBIS
PORTE                   =0x0E  ; for IN/OUT, CBI/SBI, SBIC/SBIS
;
; Port D
PIND                    =0x09  ; for IN/OUT, CBI/SBI, SBIC/SBIS
DDRD                    =0x0A  ; for IN/OUT, CBI/SBI, SBIC/SBIS
PORTD                   =0x0B  ; for IN/OUT, CBI/SBI, SBIC/SBIS
;
; Port C
PINC                    =0x06  ; for IN/OUT, CBI/SBI, SBIC/SBIS
DDRC                    =0x07  ; for IN/OUT, CBI/SBI, SBIC/SBIS
PORTC                   =0x08  ; for IN/OUT, CBI/SBI, SBIC/SBIS
;
; Port B
PINB                    =0x03  ; for IN/OUT, CBI/SBI, SBIC/SBIS
DDRB                    =0x04  ; for IN/OUT, CBI/SBI, SBIC/SBIS
PORTB                   =0x05  ; for IN/OUT, CBI/SBI, SBIC/SBIS
;
; Port A
PINA                    =0x00  ; for IN/OUT, CBI/SBI, SBIC/SBIS
DDRA                    =0x01  ; for IN/OUT, CBI/SBI, SBIC/SBIS
PORTA                   =0x02  ; for IN/OUT, CBI/SBI, SBIC/SBIS
;
; ADC
ADC                     =0x78  ; memory mapped, for LD/ST
ADCL                    =0x78  ; memory mapped, for LD/ST
ADCH                    =0x79  ; memory mapped, for LD/ST
ADCSRA                  =0x7A  ; memory mapped, for LD/ST
ADEN                    =7
ADSC                    =6
ADATE                   =5
ADIF                    =4
ADIE                    =3
ADPS2                   =2
ADPS1                   =1
ADPS0                   =0
ADCSRB                  =0x7B  ; memory mapped, for LD/ST
ADHSM                   =7
ACME                    =6
ADTS2                   =2
ADTS1                   =1
ADTS0                   =0
ADMUX                   =0x7C  ; memory mapped, for LD/ST
REFS1                   =7
REFS0                   =6
ADLAR                   =5
MUX4                    =4
MUX3                    =3
MUX2                    =2
MUX1                    =1
MUX0                    =0
;
; Analog Comparator Control and Status Register
ACSR                    =0x30  ; for IN/OUT
ACD                     =7
ACBG                    =6
ACO                     =5
ACI                     =4
ACIE                    =3
ACIC                    =2
ACIS1                   =1
ACIS0                   =0
;
; DIDR
DIDR0                   =0x7E  ; memory mapped, for LD/ST
ADC7D                   =7
ADC6D                   =6
ADC5D                   =5
ADC4D                   =4
ADC3D                   =3
ADC2D                   =2
ADC1D                   =1
ADC0D                   =0
DIDR1                   =0x7F  ; memory mapped, for LD/ST
AIN1D                   =1
AIN0D                   =0
;
; USART1 - as by datasheet
UBRR1H                  =0xCD  ; memory mapped, for LD/ST
UBRR1L                  =0xCC  ; memory mapped, for LD/ST
UBRR1                   =0xCC  ; memory mapped, for LD/ST
UCSR1C                  =0xCA  ; memory mapped, for LD/ST
UMSEL11                 =7
UMSEL10                 =6
UPM11                   =5
UPM10                   =4
USBS1                   =3
UCSZ11                  =2
UCSZ10                  =1
UCPOL1                  =0
;
; in SPI mode
UDORD1                  =2
UCPHA1                  =1
UCSR1B                  =0xC9  ; memory mapped, for LD/ST
RXCIE1                  =7
TXCIE1                  =6
UDRIE1                  =5
RXEN1                   =4
TXEN1                   =3
UCSZ12                  =2
RXB81                   =1
TXB81                   =0
UCSR1A                  =0xC8  ; memory mapped, for LD/ST
RXC1                    =7
TXC1                    =6
UDRE1                   =5
FE1                     =4
DOR1                    =3
UPE1                    =2
U2X1                    =1
MPCM1                   =0
UDR1                    =0xCE  ; memory mapped, for LD/ST
;
; USART0 - to ease port of existing code
UBRR0H                  =0xCD  ; memory mapped, for LD/ST
UBRR0L                  =0xCC  ; memory mapped, for LD/ST
UBRR0                   =0xCC  ; memory mapped, for LD/ST
UCSR0C                  =0xCA  ; memory mapped, for LD/ST
UMSEL01                 =7
UMSEL00                 =6
UPM01                   =5
UPM00                   =4
USBS0                   =3
UCSZ01                  =2
UCSZ00                  =1
UCPOL0                  =0
;
; in SPI mode
UDORD0                  =2
UCPHA0                  =1
UCSR0B                  =0xC9  ; memory mapped, for LD/ST
RXCIE0                  =7
TXCIE0                  =6
UDRIE0                  =5
RXEN0                   =4
TXEN0                   =3
UCSZ02                  =2
RXB80                   =1
TXB80                   =0
UCSR0A                  =0xC8  ; memory mapped, for LD/ST
RXC0                    =7
TXC0                    =6
UDRE0                   =5
FE0                     =4
DOR0                    =3
UPE0                    =2
U2X0                    =1
MPCM0                   =0
UDR0                    =0xCE  ; memory mapped, for LD/ST
;
; USART - to ease port of existing code
UBRRH                   =0xCD  ; memory mapped, for LD/ST
UBRRL                   =0xCC  ; memory mapped, for LD/ST
UBRR                    =0xCC  ; memory mapped, for LD/ST
UCSRC                   =0xCA  ; memory mapped, for LD/ST
UMSEL1                  =7
UMSEL0                  =6
UPM1                    =5
UPM0                    =4
USBS                    =3
UCSZ1                   =2
UCSZ0                   =1
UCPOL                   =0
;
; in SPI mode
UDORD                   =2
UCPHA                   =1
UCSRB                   =0xC9  ; memory mapped, for LD/ST
RXCIE                   =7
TXCIE                   =6
UDRIE                   =5
RXEN                    =4
TXEN                    =3
UCSZ2                   =2
RXB8                    =1
TXB8                    =0
UCSRA                   =0xC8  ; memory mapped, for LD/ST
RXC                     =7
TXC                     =6
UDRE                    =5
FE                      =4
DOR                     =3
PE                      =2
UPE                     =2
U2X                     =1
MPCM                    =0
UDR                     =0xCE  ; memory mapped, for LD/ST
;
; 2-wire SI
TWBR                    =0xB8  ; memory mapped, for LD/ST
TWSR                    =0xB9  ; memory mapped, for LD/ST
TWPS1                   =1
TWPS0                   =0
TWAR                    =0xBA  ; memory mapped, for LD/ST
TWGCE                   =0
TWDR                    =0xBB  ; memory mapped, for LD/ST
TWCR                    =0xBC  ; memory mapped, for LD/ST
TWINT                   =7
TWEA                    =6
TWSTA                   =5
TWSTO                   =4
TWWC                    =3
TWEN                    =2
TWIE                    =0
TWAMR                   =0xBD  ; memory mapped, for LD/ST
;
; SPI
SPCR                    =0x2C  ; for IN/OUT
SPIE                    =7
SPE                     =6
DORD                    =5
MSTR                    =4
CPOL                    =3
CPHA                    =2
SPR1                    =1
SPR0                    =0
SPSR                    =0x2D  ; for IN/OUT
SPIF                    =7
WCOL                    =6
SPI2X                   =0
SPDR                    =0x2E  ; for IN/OUT
;
; EEPROM
EECR                    =0x1F  ; for IN/OUT, CBI/SBI, SBIC/SBIS
EEPM1                   =5
EEPM0                   =4
EERIE                   =3
EEMPE                   =2
EEMWE                   =2
EEPE                    =1
EEWE                    =1
EERE                    =0
EEDR                    =0x20  ; for IN/OUT, CBI/SBI, SBIC/SBIS
EEAR                    =0x21  ; for IN/OUT
EEARL                   =0x21  ; for IN/OUT
EEARH                   =0x22  ; for IN/OUT
;
; GTCCR
GTCCR                   =0x23  ; for IN/OUT
TSM                     =7
PSRASY                  =1
PSRSYNC                 =0
;
; Watchdog Timer Control Register
WDTCSR                  =0x60  ; memory mapped, for LD/ST
WDTCR                   =0x60  ; memory mapped, for LD/ST
WDIF                    =7
WDIE                    =6
WDP3                    =5
WDCE                    =4
WDE                     =3
WDP2                    =2
WDP1                    =1
WDP0                    =0
;
; OCDR
OCDR                    =0x31  ; for IN/OUT
MONDR                   =0x31  ; for IN/OUT
;
; Timer/Counter 0
OCR0B                   =0x28  ; for IN/OUT
OCR0A                   =0x27  ; for IN/OUT
TCNT0                   =0x26  ; for IN/OUT
TCCR0B                  =0x25  ; for IN/OUT
FOC0A                   =7
FOC0B                   =6
WGM02                   =3
CS02                    =2
CS01                    =1
CS00                    =0
TCCR0A                  =0x24  ; for IN/OUT
COM0A1                  =7
COM0A0                  =6
COM0B1                  =5
COM0B0                  =4
WGM01                   =1
WGM00                   =0
;
; Timer/Counter1
ICR1                    =0x86  ; memory mapped, for LD/ST
ICR1L                   =0x86  ; memory mapped, for LD/ST
ICR1H                   =0x87  ; memory mapped, for LD/ST
OCR1C                   =0x8C  ; memory mapped, for LD/ST
OCR1CL                  =0x8C  ; memory mapped, for LD/ST
OCR1CH                  =0x8D  ; memory mapped, for LD/ST
OCR1B                   =0x8A  ; memory mapped, for LD/ST
OCR1BL                  =0x8A  ; memory mapped, for LD/ST
OCR1BH                  =0x8B  ; memory mapped, for LD/ST
OCR1A                   =0x88  ; memory mapped, for LD/ST
OCR1AL                  =0x88  ; memory mapped, for LD/ST
OCR1AH                  =0x89  ; memory mapped, for LD/ST
TCNT1                   =0x84  ; memory mapped, for LD/ST
TCNT1L                  =0x84  ; memory mapped, for LD/ST
TCNT1H                  =0x85  ; memory mapped, for LD/ST
TCCR1C                  =0x82  ; memory mapped, for LD/ST
FOC1A                   =7
FOC1B                   =6
FOC1C                   =5
TCCR1B                  =0x81  ; memory mapped, for LD/ST
ICNC1                   =7
ICES1                   =6
WGM13                   =4
WGM12                   =3
CS12                    =2
CS11                    =1
CS10                    =0
TCCR1A                  =0x80  ; memory mapped, for LD/ST
COM1A1                  =7
COM1A0                  =6
COM1B1                  =5
COM1B0                  =4
COM1C1                  =3
COM1C0                  =2
WGM11                   =1
WGM10                   =0
;
; Timer/Counter2
ASSR                    =0xB6  ; memory mapped, for LD/ST
EXCLK                   =6
AS2                     =5
TCN2UB                  =4
OCR2AUB                 =3
OCR2BUB                 =2
TCR2AUB                 =1
TCR2BUB                 =0
OCR2B                   =0xB4  ; memory mapped, for LD/ST
OCR2A                   =0xB3  ; memory mapped, for LD/ST
TCNT2                   =0xB2  ; memory mapped, for LD/ST
TCCR2B                  =0xB1  ; memory mapped, for LD/ST
FOC2A                   =7
FOC2B                   =6
WGM22                   =3
CS22                    =2
CS21                    =1
CS20                    =0
TCCR2A                  =0xB0  ; memory mapped, for LD/ST
COM2A1                  =7
COM2A0                  =6
COM2B1                  =5
COM2B0                  =4
WGM21                   =1
WGM20                   =0
;
; Timer/Counter3
OCR3CH                  =0x9D  ; memory mapped, for LD/ST
OCR3CL                  =0x9C  ; memory mapped, for LD/ST
OCR3C                   =0x9C  ; memory mapped, for LD/ST
OCR3BH                  =0x9B  ; memory mapped, for LD/ST
OCR3BL                  =0x9A  ; memory mapped, for LD/ST
OCR3B                   =0x9A  ; memory mapped, for LD/ST
OCR3AH                  =0x99  ; memory mapped, for LD/ST
OCR3AL                  =0x98  ; memory mapped, for LD/ST
OCR3A                   =0x98  ; memory mapped, for LD/ST
ICR3H                   =0x97  ; memory mapped, for LD/ST
ICR3L                   =0x96  ; memory mapped, for LD/ST
ICR3                    =0x96  ; memory mapped, for LD/ST
TCNT3H                  =0x95  ; memory mapped, for LD/ST
TCNT3L                  =0x94  ; memory mapped, for LD/ST
TCNT3                   =0x94  ; memory mapped, for LD/ST
TCCR3C                  =0x92  ; memory mapped, for LD/ST
FOC3A                   =7
FOC3B                   =6
FOC3C                   =5
TCCR3B                  =0x91  ; memory mapped, for LD/ST
ICNC3                   =7
ICES3                   =6
WGM33                   =4
WGM32                   =3
CS32                    =2
CS31                    =1
CS30                    =0
TCCR3A                  =0x90  ; memory mapped, for LD/ST
COM3A1                  =7
COM3A0                  =6
COM3B1                  =5
COM3B0                  =4
COM3C1                  =3
COM3C0                  =2
WGM31                   =1
WGM30                   =0
;
; Oscillator Calibration Register
OSCCAL                  =0x66  ; memory mapped, for LD/ST
;
; clock prescaler control register
CLKPR                   =0x61  ; memory mapped, for LD/ST
CLKPCE                  =7
CLKPS3                  =3
CLKPS2                  =2
CLKPS1                  =1
CLKPS0                  =0
;
; PLL control register
PLLCSR                  =0x29  ; for IN/OUT
PLLP2                   =4
PLLP1                   =3
PLLP0                   =2
PLLE                    =1
PLOCK                   =0
;
; PRR
PRR0                    =0x64  ; memory mapped, for LD/ST
PRTWI                   =7
PRTIM2                  =6
PRTIM0                  =5
PRTIM1                  =3
PRSPI                   =2
PRADC                   =0
PRR1                    =0x65  ; memory mapped, for LD/ST
PRUSB                   =7
PRTIM3                  =3
PRUSART1                =0
;
; MCU
MCUSR                   =0x34  ; for IN/OUT
JTRF                    =4
WDRF                    =3
BORF                    =2
EXTRF                   =1
PORF                    =0
MCUCR                   =0x35  ; for IN/OUT
JTD                     =7
PUD                     =4
IVSEL                   =1
IVCE                    =0
SMCR                    =0x33  ; for IN/OUT
SM2                     =3
SM1                     =2
SM0                     =1
SE                      =0
;
; SPM Control and Status Register
SPMCSR                  =0x37  ; for IN/OUT
SPMIE                   =7
RWWSB                   =6
SIGRD                   =5
RWWSRE                  =4
BLBSET                  =3
PGWRT                   =2
PGERS                   =1
SPMEN                   =0
;
; Timer/Counter Interrupts
TIFR0                   =0x15  ; for IN/OUT, CBI/SBI, SBIC/SBIS
OCF0B                   =2
OCF0A                   =1
TOV0                    =0
TIMSK0                  =0x6E  ; memory mapped, for LD/ST
OCIE0B                  =2
OCIE0A                  =1
TOIE0                   =0
TIFR1                   =0x16  ; for IN/OUT, CBI/SBI, SBIC/SBIS
ICF1                    =5
OCF1C                   =3
OCF1B                   =2
OCF1A                   =1
TOV1                    =0
TIMSK1                  =0x6F  ; memory mapped, for LD/ST
ICIE1                   =5
OCIE1C                  =3
OCIE1B                  =2
OCIE1A                  =1
TOIE1                   =0
TIFR2                   =0x17  ; for IN/OUT, CBI/SBI, SBIC/SBIS
OCF2B                   =2
OCF2A                   =1
TOV2                    =0
TIMSK2                  =0x70  ; memory mapped, for LD/ST
OCIE2B                  =2
OCIE2A                  =1
TOIE2                   =0
TIFR3                   =0x18  ; for IN/OUT, CBI/SBI, SBIC/SBIS
ICF3                    =5
OCF3C                   =3
OCF3B                   =2
OCF3A                   =1
TOV3                    =0
TIMSK3                  =0x71  ; memory mapped, for LD/ST
ICIE3                   =5
OCIE3C                  =3
OCIE3B                  =2
OCIE3A                  =1
TOIE3                   =0
;
; External Interrupts
EIFR                    =0x1C  ; for IN/OUT, CBI/SBI, SBIC/SBIS
INTF7                   =7
INTF6                   =6
INTF5                   =5
INTF4                   =4
INTF3                   =3
INTF2                   =2
INTF1                   =1
INTF0                   =0
EIMSK                   =0x1D  ; for IN/OUT, CBI/SBI, SBIC/SBIS
INT7                    =7
INT6                    =6
INT5                    =5
INT4                    =4
INT3                    =3
INT2                    =2
INT1                    =1
INT0                    =0
EICRB                   =0x6A  ; memory mapped, for LD/ST
ISC71                   =7
ISC70                   =6
ISC61                   =5
ISC60                   =4
ISC51                   =3
ISC50                   =2
ISC41                   =1
ISC40                   =0
EICRA                   =0x69  ; memory mapped, for LD/ST
ISC31                   =7
ISC30                   =6
ISC21                   =5
ISC20                   =4
ISC11                   =3
ISC10                   =2
ISC01                   =1
ISC00                   =0
;
; Pin Change Interrupts
PCIFR                   =0x1B  ; for IN/OUT, CBI/SBI, SBIC/SBIS
PCIF0                   =0
PCICR                   =0x68  ; memory mapped, for LD/ST
PCIE0                   =0
PCMSK0                  =0x6B  ; memory mapped, for LD/ST
;
; eXternal Memory Control Register
XMCRB                   =0x75  ; memory mapped, for LD/ST
XMBK                    =7
XMM2                    =2
XMM1                    =1
XMM0                    =0
XMCRA                   =0x74  ; memory mapped, for LD/ST
SRE                     =7
SRL2                    =6
SRL1                    =5
SRL0                    =4
SRW11                   =3
SRW10                   =2
SRW01                   =1
SRW00                   =0
;
; GPIO
GPIOR0                  =0x1E  ; for IN/OUT, CBI/SBI, SBIC/SBIS
GPIOR1                  =0x2A  ; for IN/OUT
GPIOR2                  =0x2B  ; for IN/OUT
;
; RAM page Z-pointer
RAMPZ                   =0x3B  ; for IN/OUT
;
; Stack Pointer
SP                      =0x3D  ; for IN/OUT
SPL                     =0x3D  ; for IN/OUT
SPH                     =0x3E  ; for IN/OUT
;
; Status REGister
SREG                    =0x3F  ; for IN/OUT
;
; io bits
;
; Port A
PORTA7                  =7
PORTA6                  =6
PORTA5                  =5
PORTA4                  =4
PORTA3                  =3
PORTA2                  =2
PORTA1                  =1
PORTA0                  =0
PA7                     =7
PA6                     =6
PA5                     =5
PA4                     =4
PA3                     =3
PA2                     =2
PA1                     =1
PA0                     =0
DDA7                    =7
DDA6                    =6
DDA5                    =5
DDA4                    =4
DDA3                    =3
DDA2                    =2
DDA1                    =1
DDA0                    =0
PINA7                   =7
PINA6                   =6
PINA5                   =5
PINA4                   =4
PINA3                   =3
PINA2                   =2
PINA1                   =1
PINA0                   =0
;
; Port B
PORTB7                  =7
PORTB6                  =6
PORTB5                  =5
PORTB4                  =4
PORTB3                  =3
PORTB2                  =2
PORTB1                  =1
PORTB0                  =0
PB7                     =7
PB6                     =6
PB5                     =5
PB4                     =4
PB3                     =3
PB2                     =2
PB1                     =1
PB0                     =0
DDB7                    =7
DDB6                    =6
DDB5                    =5
DDB4                    =4
DDB3                    =3
DDB2                    =2
DDB1                    =1
DDB0                    =0
PINB7                   =7
PINB6                   =6
PINB5                   =5
PINB4                   =4
PINB3                   =3
PINB2                   =2
PINB1                   =1
PINB0                   =0
;
; Port C
PORTC7                  =7
PORTC6                  =6
PORTC5                  =5
PORTC4                  =4
PORTC3                  =3
PORTC2                  =2
PORTC1                  =1
PORTC0                  =0
PC7                     =7
PC6                     =6
PC5                     =5
PC4                     =4
PC3                     =3
PC2                     =2
PC1                     =1
PC0                     =0
DDC7                    =7
DDC6                    =6
DDC5                    =5
DDC4                    =4
DDC3                    =3
DDC2                    =2
DDC1                    =1
DDC0                    =0
PINC7                   =7
PINC6                   =6
PINC5                   =5
PINC4                   =4
PINC3                   =3
PINC2                   =2
PINC1                   =1
PINC0                   =0
;
; Port D
PORTD7                  =7
PORTD6                  =6
PORTD5                  =5
PORTD4                  =4
PORTD3                  =3
PORTD2                  =2
PORTD1                  =1
PORTD0                  =0
PD7                     =7
PD6                     =6
PD5                     =5
PD4                     =4
PD3                     =3
PD2                     =2
PD1                     =1
PD0                     =0
DDD7                    =7
DDD6                    =6
DDD5                    =5
DDD4                    =4
DDD3                    =3
DDD2                    =2
DDD1                    =1
DDD0                    =0
PIND7                   =7
PIND6                   =6
PIND5                   =5
PIND4                   =4
PIND3                   =3
PIND2                   =2
PIND1                   =1
PIND0                   =0
;
; Port E
PORTE7                  =7
PORTE6                  =6
PORTE5                  =5
PORTE4                  =4
PORTE3                  =3
PORTE2                  =2
PORTE1                  =1
PORTE0                  =0
PE7                     =7
PE6                     =6
PE5                     =5
PE4                     =4
PE3                     =3
PE2                     =2
PE1                     =1
PE0                     =0
DDE7                    =7
DDE6                    =6
DDE5                    =5
DDE4                    =4
DDE3                    =3
DDE2                    =2
DDE1                    =1
DDE0                    =0
PINE7                   =7
PINE6                   =6
PINE5                   =5
PINE4                   =4
PINE3                   =3
PINE2                   =2
PINE1                   =1
PINE0                   =0
;
; Port F
PORTF7                  =7
PORTF6                  =6
PORTF5                  =5
PORTF4                  =4
PORTF3                  =3
PORTF2                  =2
PORTF1                  =1
PORTF0                  =0
PF7                     =7
PF6                     =6
PF5                     =5
PF4                     =4
PF3                     =3
PF2                     =2
PF1                     =1
PF0                     =0
DDF7                    =7
DDF6                    =6
DDF5                    =5
DDF4                    =4
DDF3                    =3
DDF2                    =2
DDF1                    =1
DDF0                    =0
PINF7                   =7
PINF6                   =6
PINF5                   =5
PINF4                   =4
PINF3                   =3
PINF2                   =2
PINF1                   =1
PINF0                   =0
;
; PCMSK0
PCINT7                  =7
PCINT6                  =6
PCINT5                  =5
PCINT4                  =4
PCINT3                  =3
PCINT2                  =2
PCINT1                  =1
PCINT0                  =0
;
; USB io (all memory mapped)
UHCON                   =0x9E  ; memory mapped, for LD/ST
RESUME                  =2
RESET                   =1
SOFEN                   =0
UHINT                   =0x9F  ; memory mapped, for LD/ST
HWUPI                   =6
HWUP                    =6
HSOFI                   =5
HSOF                    =5
RXRSMI                  =4
RSMEDI                  =3
RSTI                    =2
DDISCI                  =1
DCONNI                  =0
UHIEN                   =0xA0  ; memory mapped, for LD/ST
HWUPE                   =6
HSOFE                   =5
RXRSME                  =4
RSMEDE                  =3
RSTE                    =2
DDISCE                  =1
DCONNE                  =0
UHADDR                  =0xA1  ; memory mapped, for LD/ST
UHFNUM                  =0xA2  ; memory mapped, for LD/ST
UHFNUML                 =0xA2  ; memory mapped, for LD/ST
UHFNUMH                 =0xA3  ; memory mapped, for LD/ST
UHFLEN                  =0xA4  ; memory mapped, for LD/ST
UPINRQX                 =0xA5  ; memory mapped, for LD/ST
UPINTX                  =0xA6  ; memory mapped, for LD/ST
FIFOCON                 =7
NAKEDI                  =6
RWAL                    =5
PERRI                   =4
TXSTPI                  =3
TXOUTI                  =2
RXSTALLI                =1
CRCERR                  =1
RXINI                   =0
UPNUM                   =0xA7  ; memory mapped, for LD/ST
UPRST                   =0xA8  ; memory mapped, for LD/ST
P6RST                   =6
P5RST                   =5
P4RST                   =4
P3RST                   =3
P2RST                   =2
P1RST                   =1
P0RST                   =0
UPCONX                  =0xA9  ; memory mapped, for LD/ST
PFREEZE                 =6
INMODE                  =5
RSTDT                   =3
PEN                     =0
UPCFG0X                 =0xAA  ; memory mapped, for LD/ST
PTYPE1                  =7
PTYPE0                  =6
PTOKEN1                 =5
PTOKEN0                 =4
PEPNUM3                 =3
PEPNUM2                 =2
PEPNUM1                 =1
PEPNUM0                 =0
UPCFG1X                 =0xAB  ; memory mapped, for LD/ST
PSIZE2                  =6
PSIZE1                  =5
PSIZE0                  =4
PBK1                    =3
PBK0                    =2
ALLOC                   =1
UPSTAX                  =0xAC  ; memory mapped, for LD/ST
CFGOK                   =7
OVERFI                  =6
UNDERFI                 =5
DTSEQ1                  =3
DTSEQ0                  =2
NBUSYBK1                =1
NBUSYBK0                =0
UPCFG2X                 =0xAD  ; memory mapped, for LD/ST
UPIENX                  =0xAE  ; memory mapped, for LD/ST
FLERRE                  =7
NAKEDE                  =6
PERRE                   =4
TXSTPE                  =3
TXOUTE                  =2
RXSTALLE                =1
RXINE                   =0
UPDATX                  =0xAF  ; memory mapped, for LD/ST
UHWCON                  =0xD7  ; memory mapped, for LD/ST
UIMOD                   =7
UIDE                    =6
UVCONE                  =4
UVREGE                  =0
USBCON                  =0xD8  ; memory mapped, for LD/ST
USBE                    =7
HOST                    =6
FRZCLK                  =5
OTGPADE                 =4
IDTE                    =1
VBUSTE                  =0
USBSTA                  =0xD9  ; memory mapped, for LD/ST
SPEED                   =3
ID                      =1
VBUS                    =0
USBINT                  =0xDA  ; memory mapped, for LD/ST
IDTI                    =1
VBUSTI                  =0
OTGCON                  =0xDD  ; memory mapped, for LD/ST
HNPREQ                  =5
SRPREQ                  =4
SRPSEL                  =3
VBUSHWC                 =2
VBUSREQ                 =1
VBUSRQC                 =0
OTGIEN                  =0xDE  ; memory mapped, for LD/ST
STOE                    =5
HNPERRE                 =4
ROLEEXE                 =3
BCERRE                  =2
VBERRE                  =1
SRPE                    =0
OTGINT                  =0xDF  ; memory mapped, for LD/ST
STOI                    =5
HNPERRI                 =4
ROLEEXI                 =3
BCERRI                  =2
VBERRI                  =1
SRPI                    =0
UDCON                   =0xE0  ; memory mapped, for LD/ST
LSM                     =2
RMWKUP                  =1
DETACH                  =0
UDINT                   =0xE1  ; memory mapped, for LD/ST
UPRSMI                  =6
EORSMI                  =5
WAKEUPI                 =4
EORSTI                  =3
SOFI                    =2
; #define  MSOFI    1  /* this one is in register summary only */
SUSPI                   =0
UDIEN                   =0xE2  ; memory mapped, for LD/ST
UPRSME                  =6
EORSME                  =5
WAKEUPE                 =4
EORSTE                  =3
SOFE                    =2
; #define  MSOFE    1  /* this one is in register summary only */
SUSPE                   =0
UDADDR                  =0xE3  ; memory mapped, for LD/ST
ADDEN                   =7
UDFNUM                  =0xE4  ; memory mapped, for LD/ST
UDFNUML                 =0xE4  ; memory mapped, for LD/ST
UDFNUMH                 =0xE5  ; memory mapped, for LD/ST
UDMFN                   =0xE6  ; memory mapped, for LD/ST
FNCERR                  =4
UEINTX                  =0xE8  ; memory mapped, for LD/ST
FIFOCON                 =7
NAKINI                  =6
RWAL                    =5
NAKOUTI                 =4
RXSTPI                  =3
RXOUTI                  =2
STALLEDI                =1
TXINI                   =0
UENUM                   =0xE9  ; memory mapped, for LD/ST
UERST                   =0xEA  ; memory mapped, for LD/ST
EPRST6                  =6
EPRST5                  =5
EPRST4                  =4
EPRST3                  =3
EPRST2                  =2
EPRST1                  =1
EPRST0                  =0
UECONX                  =0xEB  ; memory mapped, for LD/ST
STALLRQ                 =5
STALLRQC                =4
RSTDT                   =3
EPEN                    =0
UECFG0X                 =0xEC  ; memory mapped, for LD/ST
EPTYPE1                 =7
EPTYPE0                 =6
EPDIR                   =0
UECFG1X                 =0xED  ; memory mapped, for LD/ST
EPSIZE2                 =6
EPSIZE1                 =5
EPSIZE0                 =4
EPBK1                   =3
EPBK0                   =2
ALLOC                   =1
UESTA0X                 =0xEE  ; memory mapped, for LD/ST
CFGOK                   =7
OVERFI                  =6
UNDERFI                 =5
DTSEQ1                  =3
DTSEQ0                  =2
NBUSYBK1                =1
NBUSYBK0                =0
UESTA1X                 =0xEF  ; memory mapped, for LD/ST
CTRLDIR                 =2
CURRBK1                 =1
CURRBK0                 =0
UEIENX                  =0xF0  ; memory mapped, for LD/ST
FLERRE                  =7
NAKINE                  =6
NAKOUTE                 =4
RXSTPE                  =3
RXOUTE                  =2
STALLEDE                =1
TXINE                   =0
UEDATX                  =0xF1  ; memory mapped, for LD/ST
UEBCX                   =0xF2  ; memory mapped, for LD/ST
UEBCLX                  =0xF2  ; memory mapped, for LD/ST
UEBCHX                  =0xF3  ; memory mapped, for LD/ST
UEINT                   =0xF4  ; memory mapped, for LD/ST
EPINT6                  =6
EPINT5                  =5
EPINT4                  =4
EPINT3                  =3
EPINT2                  =2
EPINT1                  =1
EPINT0                  =0
UPERRX                  =0xF5  ; memory mapped, for LD/ST
COUNTER1                =6
COUNTER0                =5
CRC16                   =4
TIMEOUT                 =3
PID                     =2
DATAPID                 =1
DATATGL                 =0
UPBCX                   =0xF6  ; memory mapped, for LD/ST
UPBCLX                  =0xF6  ; memory mapped, for LD/ST
UPBCHX                  =0xF7  ; memory mapped, for LD/ST
UPINT                   =0xF8  ; memory mapped, for LD/ST
PINT6                   =6
PINT5                   =5
PINT4                   =4
PINT3                   =3
PINT2                   =2
PINT1                   =1
PINT0                   =0
OTGTCON                 =0xF9  ; memory mapped, for LD/ST
PAGE1                   =6
PAGE0                   =5
VALUE1                  =1
VALUE0                  =0
;
; Lock and Fuse Bits with LPM/SPM instructions
;
; lock bits
BLB12                   =5
BLB11                   =4
BLB02                   =3
BLB01                   =2
LB2                     =1
LB1                     =0
;
; fuses low bits
CKDIV8                  =7
CKOUT                   =6
SUT1                    =5
SUT0                    =4
CKSEL3                  =3
CKSEL2                  =2
CKSEL1                  =1
CKSEL0                  =0
;
; fuses high bits
OCDEN                   =7
JTAGEN                  =6
SPIEN                   =5
WDTON                   =4
EESAVE                  =3
BOOTSZ1                 =2
BOOTSZ0                 =1
BOOTRST                 =0
;
; extended fuses
HWBE                    =3
BODLEVEL2               =2
BODLEVEL1               =1
BODLEVEL0               =0
;
; ------------------------------------------------------------
;
; Interrupt Vector Macros
;
.macro set_vector_INT0
 .area vector (abs)
 .org  0x04
  jmp  @0
 .area text
.endmacro
.macro set_vector_EXT_INT0
 .area vector (abs)
 .org  0x04
  jmp  @0
 .area text
.endmacro
.macro set_vector_INT1
 .area vector (abs)
 .org  0x08
  jmp  @0
 .area text
.endmacro
.macro set_vector_EXT_INT1
 .area vector (abs)
 .org  0x08
  jmp  @0
 .area text
.endmacro
.macro set_vector_INT2
 .area vector (abs)
 .org  0x0C
  jmp  @0
 .area text
.endmacro
.macro set_vector_EXT_INT2
 .area vector (abs)
 .org  0x0C
  jmp  @0
 .area text
.endmacro
.macro set_vector_INT3
 .area vector (abs)
 .org  0x10
  jmp  @0
 .area text
.endmacro
.macro set_vector_EXT_INT3
 .area vector (abs)
 .org  0x10
  jmp  @0
 .area text
.endmacro
.macro set_vector_INT4
 .area vector (abs)
 .org  0x14
  jmp  @0
 .area text
.endmacro
.macro set_vector_EXT_INT4
 .area vector (abs)
 .org  0x14
  jmp  @0
 .area text
.endmacro
.macro set_vector_INT5
 .area vector (abs)
 .org  0x18
  jmp  @0
 .area text
.endmacro
.macro set_vector_EXT_INT5
 .area vector (abs)
 .org  0x18
  jmp  @0
 .area text
.endmacro
.macro set_vector_INT6
 .area vector (abs)
 .org  0x1C
  jmp  @0
 .area text
.endmacro
.macro set_vector_EXT_INT6
 .area vector (abs)
 .org  0x1C
  jmp  @0
 .area text
.endmacro
.macro set_vector_INT7
 .area vector (abs)
 .org  0x20
  jmp  @0
 .area text
.endmacro
.macro set_vector_EXT_INT7
 .area vector (abs)
 .org  0x20
  jmp  @0
 .area text
.endmacro
.macro set_vector_PCINT0
 .area vector (abs)
 .org  0x24
  jmp  @0
 .area text
.endmacro
.macro set_vector_USB_GENERAL
 .area vector (abs)
 .org  0x28
  jmp  @0
 .area text
.endmacro
.macro set_vector_USB_GEN
 .area vector (abs)
 .org  0x28
  jmp  @0
 .area text
.endmacro
.macro set_vector_USB_END_PIPE
 .area vector (abs)
 .org  0x2C
  jmp  @0
 .area text
.endmacro
.macro set_vector_USB_EP
 .area vector (abs)
 .org  0x2C
  jmp  @0
 .area text
.endmacro
.macro set_vector_WDT
 .area vector (abs)
 .org  0x30
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIMER2_COMPA
 .area vector (abs)
 .org  0x34
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIMER2_COMPB
 .area vector (abs)
 .org  0x38
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIMER2_OVF
 .area vector (abs)
 .org  0x3C
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIM2_COMPA
 .area vector (abs)
 .org  0x34
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIM2_COMPB
 .area vector (abs)
 .org  0x38
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIM2_OVF
 .area vector (abs)
 .org  0x3C
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIMER1_CAPT
 .area vector (abs)
 .org  0x40
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIMER1_COMPA
 .area vector (abs)
 .org  0x44
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIMER1_COMPB
 .area vector (abs)
 .org  0x48
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIMER1_COMPC
 .area vector (abs)
 .org  0x4C
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIMER1_OVF
 .area vector (abs)
 .org  0x50
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIM1_CAPT
 .area vector (abs)
 .org  0x40
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIM1_COMPA
 .area vector (abs)
 .org  0x44
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIM1_COMPB
 .area vector (abs)
 .org  0x48
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIM1_COMPC
 .area vector (abs)
 .org  0x4C
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIM1_OVF
 .area vector (abs)
 .org  0x50
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIMER0_COMPA
 .area vector (abs)
 .org  0x54
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIMER0_COMPB
 .area vector (abs)
 .org  0x58
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIMER0_OVF
 .area vector (abs)
 .org  0x5C
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIM0_COMPA
 .area vector (abs)
 .org  0x54
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIM0_COMPB
 .area vector (abs)
 .org  0x58
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIM0_OVF
 .area vector (abs)
 .org  0x5C
  jmp  @0
 .area text
.endmacro
.macro set_vector_SPI_STC
 .area vector (abs)
 .org  0x60
  jmp  @0
 .area text
.endmacro
.macro set_vector_USART0_RX
 .area vector (abs)
 .org  0x64
  jmp  @0
 .area text
.endmacro
.macro set_vector_USART0_RXC
 .area vector (abs)
 .org  0x64
  jmp  @0
 .area text
.endmacro
.macro set_vector_USART0_DRE
 .area vector (abs)
 .org  0x68
  jmp  @0
 .area text
.endmacro
.macro set_vector_USART0_UDRE
 .area vector (abs)
 .org  0x68
  jmp  @0
 .area text
.endmacro
.macro set_vector_USART0_TX
 .area vector (abs)
 .org  0x6C
  jmp  @0
 .area text
.endmacro
.macro set_vector_USART0_TXC
 .area vector (abs)
 .org  0x6C
  jmp  @0
 .area text
.endmacro
.macro set_vector_USART1_RX
 .area vector (abs)
 .org  0x64
  jmp  @0
 .area text
.endmacro
.macro set_vector_USART1_RXC
 .area vector (abs)
 .org  0x64
  jmp  @0
 .area text
.endmacro
.macro set_vector_USART1_DRE
 .area vector (abs)
 .org  0x68
  jmp  @0
 .area text
.endmacro
.macro set_vector_USART1_UDRE
 .area vector (abs)
 .org  0x68
  jmp  @0
 .area text
.endmacro
.macro set_vector_USART1_TX
 .area vector (abs)
 .org  0x6C
  jmp  @0
 .area text
.endmacro
.macro set_vector_USART1_TXC
 .area vector (abs)
 .org  0x6C
  jmp  @0
 .area text
.endmacro
.macro set_vector_ANA_COMP
 .area vector (abs)
 .org  0x70
  jmp  @0
 .area text
.endmacro
.macro set_vector_ANALOG_COMP
 .area vector (abs)
 .org  0x70
  jmp  @0
 .area text
.endmacro
.macro set_vector_ADC
 .area vector (abs)
 .org  0x74
  jmp  @0
 .area text
.endmacro
.macro set_vector_EE_RDY
 .area vector (abs)
 .org  0x78
  jmp  @0
 .area text
.endmacro
.macro set_vector_EE_READY
 .area vector (abs)
 .org  0x78
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIMER3_CAPT
 .area vector (abs)
 .org  0x7C
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIMER3_COMPA
 .area vector (abs)
 .org  0x80
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIMER3_COMPB
 .area vector (abs)
 .org  0x84
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIMER3_COMPC
 .area vector (abs)
 .org  0x88
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIMER3_OVF
 .area vector (abs)
 .org  0x8C
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIM3_CAPT
 .area vector (abs)
 .org  0x7C
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIM3_COMPA
 .area vector (abs)
 .org  0x80
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIM3_COMPB
 .area vector (abs)
 .org  0x84
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIM3_COMPC
 .area vector (abs)
 .org  0x88
  jmp  @0
 .area text
.endmacro
.macro set_vector_TIM3_OVF
 .area vector (abs)
 .org  0x8C
  jmp  @0
 .area text
.endmacro
.macro set_vector_TWI
 .area vector (abs)
 .org  0x90
  jmp  @0
 .area text
.endmacro
.macro set_vector_TWSI
 .area vector (abs)
 .org  0x90
  jmp  @0
 .area text
.endmacro
.macro set_vector_SPM_RDY
 .area vector (abs)
 .org  0x94
  jmp  @0
 .area text
.endmacro
.macro set_vector_SPM_READY
 .area vector (abs)
 .org  0x94
  jmp  @0
 .area text
.endmacro
;------
;<eof>
